// Package emitter. emitter.go - Generates Go source code for Clone() method implementations
// from parsed struct definitions and their doppel struct tags, and applies gofmt-style
// formatting to ensure idiomatic output.
package emitter

import (
	"bytes"
	"fmt"
	"sort"
	"strings"

	"github.com/seyallius/doppel/cmd/doppelgen/internal/types"
	"golang.org/x/tools/imports"
)

// -------------------------------------------- Types --------------------------------------------

// Emitter holds state for a single code generation run, managing buffered output, imports, and indentation.
type Emitter struct {
	buf     bytes.Buffer
	imports map[string]types.ImportSpec
	indent  int
}

// -------------------------------------------- Public API --------------------------------------------

// Generate produces the complete Go source file content for a Clone() method implementation.
// It builds the AST-equivalent string, collects imports, emits the method body, and applies
// gofmt-style formatting before returning the final string. Returns an error if formatting fails.
func Generate(structInfo *types.StructInfo) (string, error) {
	e := &Emitter{
		imports: make(map[string]types.ImportSpec),
		indent:  0,
	}

	e.emitHeader(structInfo)
	e.emitBlankLine()
	e.emitPackage(structInfo.Package)
	e.emitBlankLine()
	e.emitImports(structInfo)
	e.emitBlankLine()

	if err := e.emitCloneMethod(structInfo); err != nil {
		return "", fmt.Errorf("emit Clone() for %s: %w", structInfo.Name, err)
	}

	// Format the generated source using Go's standard formatter.
	raw := strings.TrimSpace(e.buf.String()) + "\n"
	formatted, err := imports.Process(structInfo.File, []byte(raw), nil)
	if err != nil {
		return raw, fmt.Errorf("format generated code for %s: %w", structInfo.Name, err)
	}

	return string(formatted), nil
}

// GeneratePreview returns a human-readable preview of what would be generated.
// Useful for CLI dry-runs without writing to disk. Applies the same formatting as Generate().
func GeneratePreview(structInfo *types.StructInfo) string {
	code, err := Generate(structInfo)
	if err != nil {
		return fmt.Sprintf("// Error generating preview for %s: %v\n", structInfo.Name, err)
	}
	return code
}

// -------------------------------------------- Internal Helpers --------------------------------------------

// -------------------------------------------- Header --------------------------------------------

// emitHeader writes the auto-generated code disclaimer and source file reference.
func (e *Emitter) emitHeader(info *types.StructInfo) {
	e.emitComment("Code generated by doppelgen. DO NOT EDIT.")
	e.emitComment(fmt.Sprintf("Source: %s", info.File))
}

// emitPackage writes the Go package declaration line.
func (e *Emitter) emitPackage(name string) {
	e.emitRaw(fmt.Sprintf("package %s", name))
}

// emitImports writes the import block, collecting and sorting required packages deterministically.
func (e *Emitter) emitImports(info *types.StructInfo) {
	// Collect required imports.
	e.collectImports(info)

	if len(e.imports) == 0 {
		return
	}

	e.emitRaw("import (")
	e.indent++

	// Sort imports for deterministic output.
	var paths []string
	for path := range e.imports {
		paths = append(paths, path)
	}
	sort.Strings(paths)

	for _, path := range paths {
		spec := e.imports[path]
		if spec.Alias != "" {
			e.emitRaw(fmt.Sprintf(`%s "%s"`, spec.Alias, path))
		} else {
			e.emitRaw(fmt.Sprintf(`"%s"`, path))
		}
	}

	e.indent--
	e.emitRaw(")")
}

// collectImports scans fields to determine which packages are required.
// Beyond the original logic it now also:
//   - Adds the import path for project-internal cross-package field types.
//   - Skips adding imports for third-party types (convention functions live in
//     the user's own package, alongside the generated file).
func (e *Emitter) collectImports(info *types.StructInfo) {
	needsManual := false
	needsCore := false

	for _, field := range info.Fields {
		// Skip and Shallow fields need no helpers.
		if field.Directive.Skip || field.Directive.Shallow {
			continue
		}

		// Third-party fields use convention functions — no new imports needed here.
		if field.IsThirdParty ||
			field.TypeCategory == types.CatThirdPartyStruct ||
			field.TypeCategory == types.CatThirdPartyPtrStruct {
			needsCore = true // core.WrapError is still used
			continue
		}

		// Internal cross-package field: add the import so generated code compiles.
		if field.ImportPath != "" {
			e.addImport(field.ImportPath)
		}
		if field.ElemImportPath != "" && !field.ElemIsThirdParty {
			e.addImport(field.ElemImportPath)
		}
		if field.ValueImportPath != "" && !field.ValueIsThirdParty {
			e.addImport(field.ValueImportPath)
		}

		switch field.TypeCategory {
		case types.CatSlice, types.CatMap, types.CatPtrPrimitive, types.CatPtrStruct:
			needsManual = true
		}

		if field.TypeCategory != types.CatPrimitive {
			needsCore = true
		}
	}

	if needsManual {
		e.addImport("github.com/seyallius/doppel/manual")
	}
	if needsCore {
		e.addImport("github.com/seyallius/doppel/core")
	}
}

// addImport registers a package path to be included in the import block.
func (e *Emitter) addImport(path string) {
	if _, ok := e.imports[path]; !ok {
		e.imports[path] = types.ImportSpec{Path: path}
	}
}

// -------------------------------------------- Clone Method --------------------------------------------

// emitCloneMethod generates the full Clone() method signature, nil guard, field cloning logic, and return statement.
func (e *Emitter) emitCloneMethod(info *types.StructInfo) error {
	// Method signature: func (x *T) Clone() (*T, error)
	e.emitBlankLine()
	e.indent = 0
	e.emitRaw(fmt.Sprintf("func (x *%s) Clone() (*%s, error) {", info.Name, info.Name))
	e.indent++

	// Nil guard.
	e.emitLine("// Nil guard: preserve nil semantics.")
	e.emitRaw("if x == nil {")
	e.indent++
	e.emitRaw("return nil, nil")
	e.indent--
	e.emitRaw("}")

	e.emitBlankLine()

	// Per-field clone logic.
	// fieldVars maps field name → generated variable name (lowercased to avoid conflicts).
	fieldVars := make(map[string]string, len(info.Fields))
	for _, field := range info.Fields {
		if !field.Directive.Skip {
			fieldVars[field.Name] = cloneVarName(field.Name)
		}

		if err := e.emitFieldClone(field, info.Name, fieldVars); err != nil {
			return fmt.Errorf("field %s: %w", field.Name, err)
		}
	}

	// Return statement.
	e.emitBlankLine()
	e.emitLine("// Construct and return the clone.")
	e.emitRaw(fmt.Sprintf("return &%s{", info.Name))
	e.indent++

	for _, field := range info.Fields {
		if field.Directive.Skip {
			continue
		}
		varName := fieldVars[field.Name]
		e.emitRaw(fmt.Sprintf("%s: %s,", field.Name, varName))
	}

	e.indent--
	e.emitRaw("}, nil")

	e.indent--
	e.emitRaw("}")

	return nil
}

// -------------------------------------------- Field Clone Logic --------------------------------------------

// emitFieldClone dispatches to the appropriate cloning strategy based on the field's doppel tag and type category.
func (e *Emitter) emitFieldClone(field types.FieldInfo, structName string, fieldVars map[string]string) error {
	varName := fieldVars[field.Name]

	switch {
	case field.Directive.Skip:
		// Omit field — it receives its zero value.
		e.emitLine(fmt.Sprintf("// Field: %s (tag: skip) — omitted, receives zero value.", field.Name))
		return nil

	case field.Directive.Shallow:
		e.emitLine(fmt.Sprintf("// Field: %s (tag: shallow) — direct assignment, shares backing data.", field.Name))
		e.emitRaw(fmt.Sprintf("%s := x.%s", varName, field.Name))
		return nil

	case field.Directive.Empty:
		return e.emitEmptyField(field, structName, varName)

	case field.Directive.Clone:
		return e.emitCloneTagField(field, structName, varName)

	default:
		// Deep (default).
		return e.emitDeepField(field, structName, varName)
	}
}

// emitEmptyField generates code that initializes an empty but non-nil container for slices, maps, or structs.
func (e *Emitter) emitEmptyField(field types.FieldInfo, structName string, varName string) error {
	e.emitLine(fmt.Sprintf("// Field: %s (tag: empty) — empty-but-non-nil value.", field.Name))

	if isPrimitiveCategory(field.TypeCategory) {
		// Primitives ignore TagEmpty — assignment is already non-nil.
		e.emitRaw(fmt.Sprintf("%s := x.%s", varName, field.Name))
		return nil
	}

	switch field.TypeCategory {
	case types.CatSlice:
		e.emitRaw(fmt.Sprintf("%s := %s{}", varName, field.Type))
	case types.CatMap:
		e.emitRaw(fmt.Sprintf("%s := %s{}", varName, field.Type))
	case types.CatPtrStruct:
		e.emitRaw(fmt.Sprintf("%s := &%s{}", varName, field.PointedToType))
	case types.CatPtrPrimitive:
		// *int{} doesn't make sense, but we emit it for consistency.
		e.emitRaw(fmt.Sprintf("%s := &%s{}", varName, field.PointedToType))
	case types.CatStruct:
		e.emitRaw(fmt.Sprintf("%s := %s{}", varName, field.Type))
	default:
		e.emitRaw(fmt.Sprintf("%s := x.%s", varName, field.Name))
	}

	return nil
}

// emitCloneTagField generates a call to a convention-based clone function (e.g., CloneUserProfile).
func (e *Emitter) emitCloneTagField(field types.FieldInfo, structName string, varName string) error {
	e.emitLine(fmt.Sprintf("// Field: %s (tag: clone) — convention-based clone function.", field.Name))

	cloneFn := fmt.Sprintf("Clone%s%s", structName, field.Name)
	e.emitRaw(fmt.Sprintf("%s, err := %s(x.%s)", varName, cloneFn, field.Name))
	e.emitRaw("if err != nil {")
	e.indent++
	e.emitRaw(fmt.Sprintf("return nil, core.WrapError(%q, err)", structName+"."+field.Name))
	e.indent--
	e.emitRaw("}")

	return nil
}

// emitDeepField generates deep cloning logic for primitives, slices, maps, pointers, and nested structs.
func (e *Emitter) emitDeepField(field types.FieldInfo, structName string, varName string) error {
	switch field.TypeCategory {
	case types.CatThirdPartyStruct, types.CatThirdPartyPtrStruct:
		return e.emitThirdPartyField(field, structName, varName)

	case types.CatPrimitive:
		e.emitLine(fmt.Sprintf("// Field: %s (primitive: %s) — direct assignment.", field.Name, field.Type))
		e.emitRaw(fmt.Sprintf("%s := x.%s", varName, field.Name))

	case types.CatStruct:
		// Value struct — call Clone() and dereference the returned pointer.
		// Clone() returns (*T, error); we need the T value, so we dereference with *.
		e.emitLine(fmt.Sprintf("// Field: %s (struct: %s) — recursive Clone(), dereference result.", field.Name, field.Type))
		e.emitRaw(fmt.Sprintf("%sPtr, err := x.%s.Clone()", varName, field.Name))
		e.emitRaw("if err != nil {")
		e.indent++
		e.emitRaw(fmt.Sprintf("return nil, core.WrapError(%q, err)", structName+"."+field.Name))
		e.indent--
		e.emitRaw("}")
		// Guard against a nil return (shouldn't happen for value receivers, but be safe).
		e.emitRaw(fmt.Sprintf("var %s %s", varName, field.Type))
		e.emitRaw(fmt.Sprintf("if %sPtr != nil {", varName))
		e.indent++
		e.emitRaw(fmt.Sprintf("%s = *%sPtr", varName, varName))
		e.indent--
		e.emitRaw("}")

	case types.CatSlice:
		elemType := field.ElemType
		switch {
		case field.ElemIsThirdParty:
			return e.emitThirdPartySliceElem(field, structName, varName)

		case field.TypeCategory == types.CatInterface || elemType == "any" || elemType == "interface{}":
			return e.emitInterfaceSliceElem(field, structName, varName)

		case isBuiltinPrimitive(elemType) || field.ElemIsPrimitiveAlias:
			e.emitLine(fmt.Sprintf("// Field: %s (tag: deep) → manual.CloneSlice with Identity[%s].", field.Name, elemType))
			e.emitRaw(fmt.Sprintf("%s, err := manual.CloneSlice(x.%s, manual.Identity[%s])", varName, field.Name, elemType))

		case isBuiltinPrimitive(elemType):
			e.emitLine(fmt.Sprintf("// Field: %s (tag: deep) → manual.CloneSlice with Identity[%s].", field.Name, elemType))
			e.emitRaw(fmt.Sprintf("%s, err := manual.CloneSlice(x.%s, manual.Identity[%s])", varName, field.Name, elemType))

		default:
			// Struct element: Clone() returns (*T, error); the closure must return (*T, error).
			// Dereference the pointer inside the closure, guarding against nil.
			e.emitLine(fmt.Sprintf("// Field: %s (tag: deep) → manual.CloneSlice with Clone(), dereference pointer result.", field.Name))
			e.emitRaw(fmt.Sprintf("%s, err := manual.CloneSlice(x.%s, func(v %s) (%s, error) {", varName, field.Name, elemType, elemType))
			e.indent++
			e.emitRaw("cloned, cloneErr := v.Clone()")
			e.emitRaw("if cloneErr != nil {")
			e.indent++
			e.emitRaw(fmt.Sprintf("return %s, cloneErr", emptyLiteralForType(elemType)))
			e.indent--
			e.emitRaw("}")
			e.emitRaw("if cloned == nil {")
			e.indent++
			e.emitRaw(fmt.Sprintf("return %s, nil", emptyLiteralForType(elemType)))
			e.indent--
			e.emitRaw("}")
			e.emitRaw(fmt.Sprintf("return %s, nil", derefIfNeeded(elemType, "cloned")))
			e.indent--
			e.emitRaw("})")
		}
		e.emitRaw("if err != nil {")
		e.indent++
		e.emitRaw(fmt.Sprintf("return nil, core.WrapError(%q, err)", structName+"."+field.Name))
		e.indent--
		e.emitRaw("}")

	case types.CatMap:
		valType := field.ValueType
		switch {
		case field.ValueIsThirdParty:
			return e.emitThirdPartyMapValue(field, structName, varName)

		case field.TypeCategory == types.CatInterface || valType == "any" || valType == "interface{}":
			return e.emitInterfaceMapValue(field, structName, varName)

		case isBuiltinPrimitive(valType) || field.ValueIsPrimitiveAlias:
			e.emitLine(fmt.Sprintf("// Field: %s (tag: deep) → manual.CloneMap with Identity[%s].", field.Name, valType))
			e.emitRaw(fmt.Sprintf("%s, err := manual.CloneMap(x.%s, manual.Identity[%s])", varName, field.Name, valType))

		case isBuiltinPrimitive(valType):
			e.emitLine(fmt.Sprintf("// Field: %s (tag: deep) → manual.CloneMap with Identity[%s].", field.Name, valType))
			e.emitRaw(fmt.Sprintf("%s, err := manual.CloneMap(x.%s, manual.Identity[%s])", varName, field.Name, valType))

		default:
			// Struct value: same dereference fix as slice.
			e.emitLine(fmt.Sprintf("// Field: %s (tag: deep) → manual.CloneMap with Clone(), dereference pointer result.", field.Name))
			e.emitRaw(fmt.Sprintf("%s, err := manual.CloneMap(x.%s, func(v %s) (%s, error) {", varName, field.Name, valType, valType))
			e.indent++
			e.emitRaw("cloned, cloneErr := v.Clone()")
			e.emitRaw("if cloneErr != nil {")
			e.indent++
			e.emitRaw(fmt.Sprintf("return %s, cloneErr", emptyLiteralForType(valType)))
			e.indent--
			e.emitRaw("}")
			e.emitRaw("if cloned == nil {")
			e.indent++
			e.emitRaw(fmt.Sprintf("return %s, nil", emptyLiteralForType(valType)))
			e.indent--
			e.emitRaw("}")
			e.emitRaw(fmt.Sprintf("return %s, nil", derefIfNeeded(valType, "cloned")))
			e.indent--
			e.emitRaw("})")
		}
		e.emitRaw("if err != nil {")
		e.indent++
		e.emitRaw(fmt.Sprintf("return nil, core.WrapError(%q, err)", structName+"."+field.Name))
		e.indent--
		e.emitRaw("}")

	case types.CatPtrPrimitive:
		e.emitLine(fmt.Sprintf("// Field: %s (tag: deep) → manual.ClonePointer with Identity[%s].", field.Name, field.PointedToType))
		e.emitRaw(fmt.Sprintf("%s, err := manual.ClonePointer(x.%s, manual.Identity[%s])", varName, field.Name, field.PointedToType))
		e.emitRaw("if err != nil {")
		e.indent++
		e.emitRaw(fmt.Sprintf("return nil, core.WrapError(%q, err)", structName+"."+field.Name))
		e.indent--
		e.emitRaw("}")

	case types.CatPtrStruct:
		// ClonePointer[T] expects func(v T) (T, error), i.e. func(v Address) (Address, error).
		// But Clone() returns (*Address, error). We must dereference inside the closure.
		e.emitLine(fmt.Sprintf("// Field: %s (tag: deep) → manual.ClonePointer with Clone(), dereference pointer result.", field.Name))
		e.emitRaw(fmt.Sprintf("%s, err := manual.ClonePointer(x.%s, func(v %s) (%s, error) {", varName, field.Name, field.PointedToType, field.PointedToType))
		e.indent++
		e.emitRaw("cloned, cloneErr := v.Clone()")
		e.emitRaw("if cloneErr != nil {")
		e.indent++
		e.emitRaw(fmt.Sprintf("return %s, cloneErr", emptyLiteralForType(field.PointedToType)))
		e.indent--
		e.emitRaw("}")
		e.emitRaw("if cloned == nil {")
		e.indent++
		e.emitRaw(fmt.Sprintf("return %s, nil", emptyLiteralForType(field.PointedToType)))
		e.indent--
		e.emitRaw("}")
		e.emitRaw(fmt.Sprintf("return %s, nil", derefIfNeeded(field.PointedToType, "cloned")))
		e.indent--
		e.emitRaw("})")
		e.emitRaw("if err != nil {")
		e.indent++
		e.emitRaw(fmt.Sprintf("return nil, core.WrapError(%q, err)", structName+"."+field.Name))
		e.indent--
		e.emitRaw("}")

	case types.CatInterface:
		return e.emitInterfaceField(field, structName, varName)

	case types.CatUnknown:
		e.emitLine(fmt.Sprintf("// Field: %s (unknown type: %s) — direct assignment.", field.Name, field.Type))
		e.emitRaw(fmt.Sprintf("%s := x.%s", varName, field.Name))

	default:
		e.emitRaw(fmt.Sprintf("%s := x.%s", varName, field.Name))
	}

	return nil
}

// emitInterfaceField emits a convention-function call for a field whose type is an interface.
// Since interface values don't have a universal Clone() method, the user must provide
// a custom clone function matching the expected signature.
//
// Generated code includes:
//   - A descriptive comment explaining why custom logic is needed.
//   - A todo comment with the exact function signature to implement.
//   - A call to the convention-named function (Clone<Struct><Field>).
//   - Proper error wrapping via core.WrapError.
func (e *Emitter) emitInterfaceField(field types.FieldInfo, structName, varName string) error {
	cloneFn := fmt.Sprintf("Clone%s%s", structName, field.Name)
	e.emitLine(fmt.Sprintf("// Field: %s (interface: %s) — interface values require custom clone logic.", field.Name, field.Type))
	e.emitLine(fmt.Sprintf("//todo(%s): implement a function with signature:", cloneFn))
	e.emitLine(fmt.Sprintf("//   func %s(src %s) (%s, error)", cloneFn, field.Type, field.Type))
	e.emitRaw(fmt.Sprintf("%s, err := %s(x.%s)", varName, cloneFn, field.Name))
	e.emitRaw("if err != nil {")
	e.indent++
	e.emitRaw(fmt.Sprintf("return nil, core.WrapError(%q, err)", structName+"."+field.Name))
	e.indent--
	e.emitRaw("}")
	return nil
}

// emitInterfaceSliceElem emits a CloneSlice call for a slice whose element type is an interface.
// The element clone function must be provided by the user since interface{} has no universal Clone().
func (e *Emitter) emitInterfaceSliceElem(field types.FieldInfo, structName, varName string) error {
	cloneFn := fmt.Sprintf("Clone%s%sElem", structName, field.Name)
	e.emitLine(fmt.Sprintf("// Field: %s (tag: deep) — slice of interface type %s.", field.Name, field.ElemType))
	e.emitLine(fmt.Sprintf("//todo(%s): implement a function with signature:", cloneFn))
	e.emitLine(fmt.Sprintf("//   func %s(src %s) (%s, error)", cloneFn, field.ElemType, field.ElemType))
	e.emitRaw(fmt.Sprintf("%s, err := manual.CloneSlice(x.%s, %s)", varName, field.Name, cloneFn))
	e.emitRaw("if err != nil {")
	e.indent++
	e.emitRaw(fmt.Sprintf("return nil, core.WrapError(%q, err)", structName+"."+field.Name))
	e.indent--
	e.emitRaw("}")
	return nil
}

// emitInterfaceMapValue emits a CloneMap call for a map whose value type is an interface.
// The value clone function must be provided by the user since interface{} has no universal Clone().
func (e *Emitter) emitInterfaceMapValue(field types.FieldInfo, structName, varName string) error {
	cloneFn := fmt.Sprintf("Clone%s%sVal", structName, field.Name)
	e.emitLine(fmt.Sprintf("// Field: %s (tag: deep) — map with interface value type %s.", field.Name, field.ValueType))
	e.emitLine(fmt.Sprintf("//todo(%s): implement a function with signature:", cloneFn))
	e.emitLine(fmt.Sprintf("//   func %s(src %s) (%s, error)", cloneFn, field.ValueType, field.ValueType))
	e.emitRaw(fmt.Sprintf("%s, err := manual.CloneMap(x.%s, %s)", varName, field.Name, cloneFn))
	e.emitRaw("if err != nil {")
	e.indent++
	e.emitRaw(fmt.Sprintf("return nil, core.WrapError(%q, err)", structName+"."+field.Name))
	e.indent--
	e.emitRaw("}")
	return nil
}

// -------------------------------------------- Helpers --------------------------------------------

// cloneVarName converts a PascalCase field name to a camelCase local variable name,
// preventing conflicts between the generated variable and the field's type name.
// For example: "Address" → "clonedAddress", "ID" → "clonedID", "Tags" → "clonedTags".
func cloneVarName(fieldName string) string {
	if fieldName == "" {
		return "cloned"
	}
	return "cloned" + strings.ToUpper(fieldName[:1]) + fieldName[1:]
}

// emitRaw writes a raw string to the buffer with the current indentation level applied.
func (e *Emitter) emitRaw(s string) {
	e.buf.WriteString(strings.Repeat("\t", e.indent))
	e.buf.WriteString(s)
	e.buf.WriteString("\n")
}

// emitLine is an alias for emitRaw used for single-line statements.
func (e *Emitter) emitLine(s string) {
	e.emitRaw(s)
}

// emitComment prepends "// " to the string and writes it as a comment line.
func (e *Emitter) emitComment(s string) {
	e.emitRaw("// " + s)
}

// emitBlankLine writes a single newline to the buffer for readability.
func (e *Emitter) emitBlankLine() {
	e.buf.WriteString("\n")
}

// isPrimitiveCategory checks if the type category represents a primitive or pointer-to-primitive.
func isPrimitiveCategory(cat types.TypeCategory) bool {
	return cat == types.CatPrimitive || cat == types.CatPtrPrimitive
}

// isBuiltinPrimitive reports whether the type name matches a Go builtin primitive type.
func isBuiltinPrimitive(t string) bool {
	switch t {
	case "bool", "byte", "complex64", "complex128",
		"error", "float32", "float64", "int", "int8",
		"int16", "int32", "int64", "rune", "string",
		"uint", "uint8", "uint16", "uint32", "uint64",
		"uintptr":
		return true
	default:
		return false
	}
}

// emptyLiteralForType returns the Go expression for an empty value of the given type.
// For pointer types (*T), returns &T{}. For value types (T), returns T{}.
func emptyLiteralForType(typeExpr string) string {
	if len(typeExpr) > 0 && typeExpr[0] == '*' {
		return "&" + typeExpr[1:] + "{}" // Pointer type: *Address → &Address{}
	}
	return typeExpr + "{}" // Value type: Address → Address{}
}

// derefIfNeeded returns the variable name, dereferencing it if the target type is a value type.
// For pointer types (*T), the variable is already *T, so return as-is.
// For value types (T), the variable is *T from Clone(), so we dereference with *.
func derefIfNeeded(typeExpr, varName string) string {
	if len(typeExpr) > 0 && typeExpr[0] == '*' {
		return varName // Already a pointer, no deref needed
	}
	return "*" + varName // Value type: dereference the *T returned by Clone()
}
