// Package emitter generates Go source code for Clone() method implementations
// from parsed struct definitions and their doppel struct tags.
package emitter

import (
	"bytes"
	"fmt"
	"sort"
	"strings"

	"github.com/seyallius/doppel/cmd/doppelgen/internal/types"
	"github.com/seyallius/doppel/core"
)

// -------------------------------------------- Types --------------------------------------------

// Emitter holds state for a single code generation run.
type Emitter struct {
	buf     bytes.Buffer
	imports map[string]types.ImportSpec
	indent  int
}

// -------------------------------------------- Public API --------------------------------------------

// Generate produces the complete Go source file content for a Clone() method
// implementation of the given struct.
func Generate(structInfo *types.StructInfo) (string, error) {
	e := &Emitter{
		imports: make(map[string]types.ImportSpec),
		indent:  0,
	}

	e.emitHeader(structInfo)
	e.emitBlankLine()
	e.emitPackage(structInfo.Package)
	e.emitBlankLine()
	e.emitImports(structInfo)
	e.emitBlankLine()

	if err := e.emitCloneMethod(structInfo); err != nil {
		return "", fmt.Errorf("emit Clone() for %s: %w", structInfo.Name, err)
	}

	return strings.TrimSpace(e.buf.String()) + "\n", nil
}

// GeneratePreview returns a human-readable preview of what would be generated.
func GeneratePreview(structInfo *types.StructInfo) string {
	code, err := Generate(structInfo)
	if err != nil {
		return fmt.Sprintf("// Error generating preview for %s: %v\n", structInfo.Name, err)
	}
	return code
}

// -------------------------------------------- Header --------------------------------------------

func (e *Emitter) emitHeader(info *types.StructInfo) {
	e.emitComment("Code generated by doppelgen. DO NOT EDIT.")
	e.emitComment(fmt.Sprintf("Source: %s", info.File))
}

func (e *Emitter) emitPackage(name string) {
	e.emitRaw(fmt.Sprintf("package %s", name))
}

func (e *Emitter) emitImports(info *types.StructInfo) {
	// Collect required imports.
	e.collectImports(info)

	if len(e.imports) == 0 {
		return
	}

	e.emitRaw("import (")
	e.indent++

	// Sort imports for deterministic output.
	var paths []string
	for path := range e.imports {
		paths = append(paths, path)
	}
	sort.Strings(paths)

	for _, path := range paths {
		spec := e.imports[path]
		if spec.Alias != "" {
			e.emitRaw(fmt.Sprintf(`%s "%s"`, spec.Alias, path))
		} else {
			e.emitRaw(fmt.Sprintf(`"%s"`, path))
		}
	}

	e.indent--
	e.emitRaw(")")
}

func (e *Emitter) collectImports(info *types.StructInfo) {
	for _, field := range info.Fields {
		switch field.Directive {
		case core.TagDirective{Skip: true}, core.TagDirective{Shallow: true}:
			continue
		}

		switch field.TypeCategory {
		case types.CatSlice, types.CatMap, types.CatPtrPrimitive:
			e.addImport("github.com/seyallius/doppel/manual")
		case types.CatPtrStruct:
			e.addImport("github.com/seyallius/doppel/manual")
		case types.CatStruct:
			// If a struct field calls .Clone(), no manual import needed
			// unless it goes through a helper.
		}
	}

	// Always need core for WrapError if there are any non-primitive fields.
	for _, field := range info.Fields {
		if field.TypeCategory != types.CatPrimitive {
			e.addImport("github.com/seyallius/doppel/core")
			break
		}
	}
}

func (e *Emitter) addImport(path string) {
	if _, ok := e.imports[path]; !ok {
		e.imports[path] = types.ImportSpec{Path: path}
	}
}

// -------------------------------------------- Clone Method --------------------------------------------

func (e *Emitter) emitCloneMethod(info *types.StructInfo) error {
	// Method signature: func (x *T) Clone() (*T, error)
	e.emitBlankLine()
	e.indent = 0
	e.emitRaw(fmt.Sprintf("func (x *%s) Clone() (*%s, error) {", info.Name, info.Name))
	e.indent++

	// Nil guard.
	e.emitLine("// Nil guard: preserve nil semantics.")
	e.emitRaw("if x == nil {")
	e.indent++
	e.emitRaw("return nil, nil")
	e.indent--
	e.emitRaw("}")

	e.emitBlankLine()

	// Per-field clone logic.
	var fieldNames []string
	for _, field := range info.Fields {
		fieldNames = append(fieldNames, field.Name)

		if err := e.emitFieldClone(field, info.Name); err != nil {
			return fmt.Errorf("field %s: %w", field.Name, err)
		}
	}

	// Return statement.
	e.emitBlankLine()
	e.emitLine("// Construct and return the clone.")
	returnLine := fmt.Sprintf("return &%s{", info.Name)
	e.emitRaw(returnLine)
	e.indent++

	for _, name := range fieldNames {
		e.emitRaw(fmt.Sprintf("%s: %s,", name, name))
	}

	e.indent--
	e.emitRaw("}, nil")

	e.indent--
	e.emitRaw("}")

	return nil
}

// -------------------------------------------- Field Clone Logic --------------------------------------------

func (e *Emitter) emitFieldClone(field types.FieldInfo, structName string) error {
	// Determine clone strategy based on tag and type.
	switch {
	case field.Directive.Skip:
		// Omit field — it receives its zero value.
		e.emitLine(fmt.Sprintf("// Field: %s (tag: skip) — omitted, receives zero value.", field.Name))
		return nil

	case field.Directive.Shallow:
		e.emitLine(fmt.Sprintf("// Field: %s (tag: shallow) — direct assignment, shares backing data.", field.Name))
		e.emitRaw(fmt.Sprintf("%s := x.%s", field.Name, field.Name))
		return nil

	case field.Directive.Empty:
		return e.emitEmptyField(field, structName)

	case field.Directive.Clone:
		return e.emitCloneTagField(field, structName)

	default:
		// Deep (default).
		return e.emitDeepField(field, structName)
	}
}

func (e *Emitter) emitEmptyField(field types.FieldInfo, structName string) error {
	e.emitLine(fmt.Sprintf("// Field: %s (tag: empty) — empty-but-non-nil value.", field.Name))

	if isPrimitiveCategory(field.TypeCategory) {
		// Primitives ignore TagEmpty — assignment is already non-nil.
		e.emitRaw(fmt.Sprintf("%s := x.%s", field.Name, field.Name))
		return nil
	}

	switch field.TypeCategory {
	case types.CatSlice:
		e.emitRaw(fmt.Sprintf("%s := %s{}", field.Name, field.Type))
	case types.CatMap:
		e.emitRaw(fmt.Sprintf("%s := %s{}", field.Name, field.Type))
	case types.CatPtrStruct:
		e.emitRaw(fmt.Sprintf("%s := &%s{}", field.Name, field.PointedToType))
	case types.CatPtrPrimitive:
		// *int{} doesn't make sense, but we emit it for consistency.
		e.emitRaw(fmt.Sprintf("%s := &%s{}", field.Name, field.PointedToType))
	case types.CatStruct:
		e.emitRaw(fmt.Sprintf("%s := %s{}", field.Name, field.Type))
	default:
		e.emitRaw(fmt.Sprintf("%s := x.%s", field.Name, field.Name))
	}

	return nil
}

func (e *Emitter) emitCloneTagField(field types.FieldInfo, structName string) error {
	e.emitLine(fmt.Sprintf("// Field: %s (tag: clone) — convention-based clone function.", field.Name))

	cloneFn := fmt.Sprintf("clone%s%s", structName, field.Name)
	e.emitRaw(fmt.Sprintf("%s, err := %s(x.%s)", field.Name, cloneFn, field.Name))
	e.emitRaw("if err != nil {")
	e.indent++
	e.emitRaw(fmt.Sprintf("return nil, core.WrapError(%q.%s, err)", structName, field.Name))
	e.indent--
	e.emitRaw("}")

	return nil
}

func (e *Emitter) emitDeepField(field types.FieldInfo, structName string) error {
	switch field.TypeCategory {
	case types.CatPrimitive:
		e.emitLine(fmt.Sprintf("// Field: %s (primitive: %s) — direct assignment.", field.Name, field.Type))
		e.emitRaw(fmt.Sprintf("%s := x.%s", field.Name, field.Name))

	case types.CatStruct:
		e.emitLine(fmt.Sprintf("// Field: %s (struct: %s) — recursive Clone().", field.Name, field.Type))
		e.emitRaw(fmt.Sprintf("%s, err := x.%s.Clone()", field.Name, field.Name))
		e.emitRaw("if err != nil {")
		e.indent++
		e.emitRaw(fmt.Sprintf("return nil, core.WrapError(%q.%s, err)", structName, field.Name))
		e.indent--
		e.emitRaw("}")

	case types.CatSlice:
		elemType := field.ElemType
		if isBuiltinPrimitive(elemType) {
			e.emitLine(fmt.Sprintf("// Field: %s (tag: deep) → manual.CloneSlice with Identity[%s].", field.Name, elemType))
			e.emitRaw(fmt.Sprintf("%s, err := manual.CloneSlice(x.%s, manual.Identity[%s])", field.Name, field.Name, elemType))
		} else {
			e.emitLine(fmt.Sprintf("// Field: %s (tag: deep) → manual.CloneSlice with Clone().", field.Name))
			e.emitRaw(fmt.Sprintf("%s, err := manual.CloneSlice(x.%s, func(v %s) (%s, error) {", field.Name, field.Name, elemType, elemType))
			e.indent++
			e.emitRaw("return v.Clone()")
			e.indent--
			e.emitRaw("})")
		}
		e.emitRaw("if err != nil {")
		e.indent++
		e.emitRaw(fmt.Sprintf("return nil, core.WrapError(%q.%s, err)", structName, field.Name))
		e.indent--
		e.emitRaw("}")

	case types.CatMap:
		valType := field.ValueType
		if isBuiltinPrimitive(valType) {
			e.emitLine(fmt.Sprintf("// Field: %s (tag: deep) → manual.CloneMap with Identity[%s].", field.Name, valType))
			e.emitRaw(fmt.Sprintf("%s, err := manual.CloneMap(x.%s, manual.Identity[%s])", field.Name, field.Name, valType))
		} else {
			e.emitLine(fmt.Sprintf("// Field: %s (tag: deep) → manual.CloneMap with Clone().", field.Name))
			e.emitRaw(fmt.Sprintf("%s, err := manual.CloneMap(x.%s, func(v %s) (%s, error) {", field.Name, field.Name, valType, valType))
			e.indent++
			e.emitRaw("return v.Clone()")
			e.indent--
			e.emitRaw("})")
		}
		e.emitRaw("if err != nil {")
		e.indent++
		e.emitRaw(fmt.Sprintf("return nil, core.WrapError(%q.%s, err)", structName, field.Name))
		e.indent--
		e.emitRaw("}")

	case types.CatPtrPrimitive:
		e.emitLine(fmt.Sprintf("// Field: %s (tag: deep) → manual.ClonePointer with Identity[%s].", field.Name, field.PointedToType))
		e.emitRaw(fmt.Sprintf("%s, err := manual.ClonePointer(x.%s, manual.Identity[%s])", field.Name, field.Name, field.PointedToType))
		e.emitRaw("if err != nil {")
		e.indent++
		e.emitRaw(fmt.Sprintf("return nil, core.WrapError(%q.%s, err)", structName, field.Name))
		e.indent--
		e.emitRaw("}")

	case types.CatPtrStruct:
		e.emitLine(fmt.Sprintf("// Field: %s (tag: deep) → manual.ClonePointer with Clone().", field.Name))
		e.emitRaw(fmt.Sprintf("%s, err := manual.ClonePointer(x.%s, func(v %s) (%s, error) {", field.Name, field.Name, field.PointedToType, field.PointedToType))
		e.indent++
		e.emitRaw("return v.Clone()")
		e.indent--
		e.emitRaw("})")
		e.emitRaw("if err != nil {")
		e.indent++
		e.emitRaw(fmt.Sprintf("return nil, core.WrapError(%q.%s, err)", structName, field.Name))
		e.indent--
		e.emitRaw("}")

	case types.CatInterface:
		e.emitLine(fmt.Sprintf("// Field: %s (interface) — direct assignment (no deep copy possible).", field.Name))
		e.emitRaw(fmt.Sprintf("%s := x.%s", field.Name, field.Name))

	case types.CatUnknown:
		e.emitLine(fmt.Sprintf("// Field: %s (unknown type: %s) — direct assignment.", field.Name, field.Type))
		e.emitRaw(fmt.Sprintf("%s := x.%s", field.Name, field.Name))

	default:
		e.emitRaw(fmt.Sprintf("%s := x.%s", field.Name, field.Name))
	}

	return nil
}

// -------------------------------------------- Helpers --------------------------------------------

func (e *Emitter) emitRaw(s string) {
	e.buf.WriteString(strings.Repeat("\t", e.indent))
	e.buf.WriteString(s)
	e.buf.WriteString("\n")
}

func (e *Emitter) emitLine(s string) {
	e.emitRaw(s)
}

func (e *Emitter) emitComment(s string) {
	e.emitRaw("// " + s)
}

func (e *Emitter) emitBlankLine() {
	e.buf.WriteString("\n")
}

func isPrimitiveCategory(cat types.TypeCategory) bool {
	return cat == types.CatPrimitive || cat == types.CatPtrPrimitive
}

func isBuiltinPrimitive(t string) bool {
	switch t {
	case "bool", "byte", "complex64", "complex128",
		"error", "float32", "float64", "int", "int8",
		"int16", "int32", "int64", "rune", "string",
		"uint", "uint8", "uint16", "uint32", "uint64",
		"uintptr":
		return true
	default:
		return false
	}
}
