// Package emitter. testgen.go - Generates Go test files for Clone() method implementations
// produced by doppelgen. Each generated test file exercises the clone method with nil guards,
// round-trip checks, deep-copy independence, skip-field zero-value verification, shallow-field
// reference sharing, and empty-field non-nil assertions.
package emitter

import (
	"bytes"
	"fmt"
	"sort"
	"strings"

	"github.com/seyallius/doppel/cmd/doppelgen/internal/types"
	"github.com/seyallius/doppel/cmd/doppelgen/pkg/utils"
	"golang.org/x/tools/imports"
)

//TODO(gen-test): Use reflection with deep checking.

// -------------------------------------------- Types --------------------------------------------

// testEmitter holds state for a single test-file generation run.
type testEmitter struct {
	buf     bytes.Buffer
	imports map[string]types.ImportSpec
	indent  int
}

// -------------------------------------------- Public API --------------------------------------------

// GenerateTest produces the complete Go test file content for a generated Clone() method.
// It creates focused sub-tests that verify nil safety, basic round-trip, deep-copy
// independence, skip-field zero values, shallow-field reference sharing, and empty-field
// non-nil semantics. Returns an error if formatting fails.
func GenerateTest(structInfo *types.StructInfo) (string, error) {
	e := &testEmitter{
		buf:     bytes.Buffer{},
		indent:  0,
		imports: make(map[string]types.ImportSpec),
	}

	e.emitHeader(structInfo)
	e.emitBlankLine()
	e.emitPackage(structInfo.Package)
	e.emitBlankLine()
	e.emitImports(structInfo)
	e.emitBlankLine()

	// Emit the ptr helper if there are pointer-to-primitive fields.
	if e.hasPtrPrimitiveFields(structInfo) {
		e.emitPtrHelper()
		e.emitBlankLine()
	}

	// Structs with "clone"-tagged fields depend on convention-based functions
	// that may not exist yet. Emit a notice and a stub test instead of full tests.
	if e.hasCloneTagFields(structInfo) {
		e.emitCloneTagStubTest(structInfo)
	} else {
		e.emitNilTest(structInfo)
		e.emitBlankLine()
		e.emitRoundTripTest(structInfo)

		// Only emit specialized sub-tests when the struct has relevant fields.
		if e.hasDeepContainerFields(structInfo) {
			e.emitBlankLine()
			e.emitDeepCopyTest(structInfo)
		}
		if e.hasSkipFields(structInfo) {
			e.emitBlankLine()
			e.emitSkipTest(structInfo)
		}
		if e.hasShallowContainerFields(structInfo) {
			e.emitBlankLine()
			e.emitShallowTest(structInfo)
		}
		if e.hasEmptyFields(structInfo) {
			e.emitBlankLine()
			e.emitEmptyTest(structInfo)
		}
	}

	// Format the generated source.
	raw := strings.TrimSpace(e.buf.String()) + "\n"
	formatted, err := imports.Process(structInfo.File, []byte(raw), nil)
	if err != nil {
		return raw, fmt.Errorf("format test code for %s: %w", structInfo.Name, err)
	}

	return string(formatted), nil
}

// -------------------------------------------- Internal Helpers --------------------------------------------

// -------------------------------------------- Header & Package --------------------------------------------

func (e *testEmitter) emitHeader(info *types.StructInfo) {
	e.emitComment("Code generated by doppelgen. DO NOT EDIT.")
	e.emitComment(fmt.Sprintf("Source: %s", info.File))
}

func (e *testEmitter) emitPackage(name string) {
	e.emitRaw(fmt.Sprintf("package %s", name))
}

// -------------------------------------------- Imports --------------------------------------------

func (e *testEmitter) emitImports(info *types.StructInfo) {
	// Test files always need "testing".
	e.imports["testing"] = types.ImportSpec{Path: "testing"}

	// We need the package under test — use its package path relative to the module.
	// Since the test file lives in the same directory, same package import is fine
	// for external test packages (package_test). However, to keep things simple and
	// to avoid needing the full import path, we use same-package tests (package testdata)
	// by default. The imports.Process call will clean up any unused imports.
	_ = info

	if len(e.imports) == 0 {
		return
	}

	e.emitRaw("import (")
	e.indent++

	var paths []string
	for path := range e.imports {
		paths = append(paths, path)
	}
	sort.Strings(paths)

	for _, path := range paths {
		e.emitRaw(fmt.Sprintf(`"%s"`, path))
	}

	e.indent--
	e.emitRaw(")")
}

// -------------------------------------------- ptr Helper --------------------------------------------

// emitPtrHelper emits a generic pointer constructor used in tests:
//
//	func ptr[T any](v T) *T { return &v }
func (e *testEmitter) emitPtrHelper() {
	e.emitRaw("func ptr[T any](v T) *T { return &v }")
}

// -------------------------------------------- Nil Test --------------------------------------------

func (e *testEmitter) emitNilTest(info *types.StructInfo) {
	e.emitRaw(fmt.Sprintf("func Test%s_Clone_Nil(t *testing.T) {", utils.ToUpperAtN(0, info.Name)))
	e.indent++
	e.emitRaw("t.Parallel()")
	e.emitBlankLine()
	e.emitRaw(fmt.Sprintf("var x *%s = nil", info.Name))
	e.emitRaw("got, err := x.Clone()")
	e.emitRaw("if err != nil {")
	e.indent++
	e.emitRaw(`t.Fatalf("Clone() returned error: %v", err)`)
	e.indent--
	e.emitRaw("}")
	e.emitRaw("if got != nil {")
	e.indent++
	e.emitRaw(`t.Error("Clone() of nil should return nil")`)
	e.indent--
	e.emitRaw("}")
	e.indent--
	e.emitRaw("}")
}

// -------------------------------------------- Round-Trip Test --------------------------------------------

func (e *testEmitter) emitRoundTripTest(info *types.StructInfo) {
	e.emitRaw(fmt.Sprintf("func Test%s_Clone(t *testing.T) {", utils.ToUpperAtN(0, info.Name)))
	e.indent++
	e.emitRaw("t.Parallel()")
	e.emitBlankLine()

	// Construct original with non-zero test values.
	e.emitRaw(fmt.Sprintf("original := &%s{", info.Name))
	e.indent++
	for _, field := range info.Fields {
		if field.Directive.Skip {
			// Initialize skip fields too so we can verify they're zeroed.
			e.emitRaw(fmt.Sprintf("%s: %s,", field.Name, testFieldValue(field)))
		} else {
			e.emitRaw(fmt.Sprintf("%s: %s,", field.Name, testFieldValue(field)))
		}
	}
	e.indent--
	e.emitRaw("}")

	e.emitBlankLine()
	e.emitRaw("clone, err := original.Clone()")
	e.emitRaw("if err != nil {")
	e.indent++
	e.emitRaw(`t.Fatalf("Clone() returned error: %v", err)`)
	e.indent--
	e.emitRaw("}")
	e.emitBlankLine()

	// Basic invariants.
	e.emitRaw("// Verify basic invariants.")
	e.emitRaw("if clone == nil {")
	e.indent++
	e.emitRaw(`t.Fatal("Clone() returned nil for non-nil input")`)
	e.indent--
	e.emitRaw("}")
	e.emitRaw("if clone == original {")
	e.indent++
	e.emitRaw(`t.Error("Clone() returned the same pointer")`)
	e.indent--
	e.emitRaw("}")

	e.indent--
	e.emitRaw("}")
}

// -------------------------------------------- Deep-Copy Independence Test --------------------------------------------

func (e *testEmitter) emitDeepCopyTest(info *types.StructInfo) {
	e.emitRaw(fmt.Sprintf("func Test%s_Clone_DeepCopyIndependence(t *testing.T) {", utils.ToUpperAtN(0, info.Name)))
	e.indent++
	e.emitRaw("t.Parallel()")
	e.emitBlankLine()

	// Construct original with non-empty deep-copied containers.
	e.emitRaw(fmt.Sprintf("original := &%s{", info.Name))
	e.indent++
	for _, field := range info.Fields {
		if !isDeepCopiedContainer(field) {
			continue
		}
		e.emitRaw(fmt.Sprintf("%s: %s,", field.Name, testFieldValue(field)))
	}
	e.indent--
	e.emitRaw("}")

	e.emitBlankLine()
	e.emitRaw("clone, err := original.Clone()")
	e.emitRaw("if err != nil {")
	e.indent++
	e.emitRaw(`t.Fatalf("Clone() returned error: %v", err)`)
	e.indent--
	e.emitRaw("}")
	e.emitBlankLine()

	// Verify independence for each deep-copied container field.
	for _, field := range info.Fields {
		if !isDeepCopiedContainer(field) {
			continue
		}
		e.emitDeepCopyAssertion(field, info.Name)
	}

	e.indent--
	e.emitRaw("}")
}

func (e *testEmitter) emitDeepCopyAssertion(field types.FieldInfo, structName string) {
	switch field.TypeCategory {
	case types.CatSlice:
		if isBuiltinPrimitive(field.ElemType) {
			e.emitRaw(fmt.Sprintf("// Mutating original.%s should not affect clone.%s.", field.Name, field.Name))
			e.emitRaw(fmt.Sprintf("original.%s[0] = %s", field.Name, alternateSliceValue(field.ElemType)))
			e.emitRaw(fmt.Sprintf("if clone.%s[0] == %s {", field.Name, alternateSliceValue(field.ElemType)))
			e.indent++
			e.emitRaw(fmt.Sprintf(`t.Error("%s should be deep-copied (independent of original)")`, field.Name))
			e.indent--
			e.emitRaw("}")
		} else {
			// Struct-element slices — just verify the slice header is different.
			e.emitRaw(fmt.Sprintf("// original.%s and clone.%s should be different slices.", field.Name, field.Name))
			e.emitRaw(fmt.Sprintf("if &original.%s[0] == &clone.%s[0] {", field.Name, field.Name))
			e.indent++
			e.emitRaw(fmt.Sprintf(`t.Error("%s slice should be deep-copied (independent of original)")`, field.Name))
			e.indent--
			e.emitRaw("}")
		}
		e.emitBlankLine()

	case types.CatMap:
		if isBuiltinPrimitive(field.ValueType) {
			e.emitRaw(fmt.Sprintf("// Mutating original.%s should not affect clone.%s.", field.Name, field.Name))
			e.emitRaw(fmt.Sprintf("original.%s[%s] = %s", field.Name, mapTestKey(field.KeyType), alternateMapValue(field.ValueType)))
			e.emitRaw(fmt.Sprintf("if clone.%s[%s] == %s {", field.Name, mapTestKey(field.KeyType), alternateMapValue(field.ValueType)))
			e.indent++
			e.emitRaw(fmt.Sprintf(`t.Error("%s should be deep-copied (independent of original)")`, field.Name))
			e.indent--
			e.emitRaw("}")
		} else {
			// Struct-value maps — just verify the map header is different.
			e.emitRaw(fmt.Sprintf("// original.%s and clone.%s should be different maps.", field.Name, field.Name))
			e.emitRaw(fmt.Sprintf("if len(original.%s) > 0 && len(clone.%s) > 0 {", field.Name, field.Name))
			e.indent++
			e.emitRaw(fmt.Sprintf("original.%s[%s] = %s{}", field.Name, mapTestKey(field.KeyType), field.ValueType))
			e.emitRaw(fmt.Sprintf("if _, ok := clone.%s[%s]; !ok {", field.Name, mapTestKey(field.KeyType)))
			e.indent++
			e.emitRaw("// clone should not have the new key — maps are independent")
			e.indent--
			e.emitRaw("}")
			e.indent--
			e.emitRaw("}")
			e.indent--
			e.emitRaw("}")
		}
		e.emitBlankLine()

	case types.CatPtrPrimitive:
		e.emitRaw(fmt.Sprintf("// original.%s and clone.%s should point to different values.", field.Name, field.Name))
		e.emitRaw(fmt.Sprintf("if original.%s != nil && clone.%s != nil && original.%s == clone.%s {", field.Name, field.Name, field.Name, field.Name))
		e.indent++
		e.emitRaw(fmt.Sprintf(`t.Error("%s should be deep-copied (independent pointer)")`, field.Name))
		e.indent--
		e.emitRaw("}")
		e.emitBlankLine()

	case types.CatPtrStruct:
		e.emitRaw(fmt.Sprintf("// original.%s and clone.%s should point to different structs.", field.Name, field.Name))
		e.emitRaw(fmt.Sprintf("if original.%s != nil && clone.%s != nil && original.%s == clone.%s {", field.Name, field.Name, field.Name, field.Name))
		e.indent++
		e.emitRaw(fmt.Sprintf(`t.Error("%s should be deep-copied (independent pointer)")`, field.Name))
		e.indent--
		e.emitRaw("}")
		e.emitBlankLine()

	case types.CatStruct:
		// Value structs that are deep-copied via .Clone() — verify field address is different.
		e.emitRaw(fmt.Sprintf("// original.%s and clone.%s should be different struct values.", field.Name, field.Name))
		e.emitRaw(fmt.Sprintf("if &original.%s == &clone.%s {", field.Name, field.Name))
		e.indent++
		e.emitRaw(fmt.Sprintf(`t.Error("%s should be deep-copied (independent struct)")`, field.Name))
		e.indent--
		e.emitRaw("}")
		e.emitBlankLine()
	}
}

// -------------------------------------------- Skip-Field Test --------------------------------------------

func (e *testEmitter) emitSkipTest(info *types.StructInfo) {
	e.emitRaw(fmt.Sprintf("func Test%s_Clone_SkipFields(t *testing.T) {", utils.ToUpperAtN(0, info.Name)))
	e.indent++
	e.emitRaw("t.Parallel()")
	e.emitBlankLine()

	// Build original with non-zero skip fields.
	e.emitRaw(fmt.Sprintf("original := &%s{", info.Name))
	e.indent++
	for _, field := range info.Fields {
		if field.Directive.Skip {
			e.emitRaw(fmt.Sprintf("%s: %s,", field.Name, testFieldValue(field)))
		}
	}
	e.indent--
	e.emitRaw("}")

	e.emitBlankLine()
	e.emitRaw("clone, err := original.Clone()")
	e.emitRaw("if err != nil {")
	e.indent++
	e.emitRaw(`t.Fatalf("Clone() returned error: %v", err)`)
	e.indent--
	e.emitRaw("}")
	e.emitBlankLine()

	// Verify each skip field has its zero value.
	for _, field := range info.Fields {
		if !field.Directive.Skip {
			continue
		}
		e.emitRaw(fmt.Sprintf("// Skip-tagged field %s should receive its zero value.", field.Name))
		e.emitRaw(fmt.Sprintf("if clone.%s != %s {", field.Name, zeroValue(field)))
		e.indent++
		e.emitRaw(fmt.Sprintf(`t.Errorf("skip field %s = %%v, want zero value", clone.%s)`, field.Name, field.Name))
		e.indent--
		e.emitRaw("}")
		e.emitBlankLine()
	}

	e.indent--
	e.emitRaw("}")
}

// -------------------------------------------- Shallow-Field Test --------------------------------------------

func (e *testEmitter) emitShallowTest(info *types.StructInfo) {
	e.emitRaw(fmt.Sprintf("func Test%s_Clone_ShallowFields(t *testing.T) {", utils.ToUpperAtN(0, info.Name)))
	e.indent++
	e.emitRaw("t.Parallel()")
	e.emitBlankLine()

	// Build original with non-zero shallow container fields.
	e.emitRaw(fmt.Sprintf("original := &%s{", info.Name))
	e.indent++
	for _, field := range info.Fields {
		if field.Directive.Shallow && isContainerType(field.TypeCategory) {
			e.emitRaw(fmt.Sprintf("%s: %s,", field.Name, testFieldValue(field)))
		}
	}
	e.indent--
	e.emitRaw("}")

	e.emitBlankLine()
	e.emitRaw("clone, err := original.Clone()")
	e.emitRaw("if err != nil {")
	e.indent++
	e.emitRaw(`t.Fatalf("Clone() returned error: %v", err)`)
	e.indent--
	e.emitRaw("}")
	e.emitBlankLine()

	// Verify each shallow container shares the same reference.
	for _, field := range info.Fields {
		if !field.Directive.Shallow || !isContainerType(field.TypeCategory) {
			continue
		}
		e.emitRaw(fmt.Sprintf("// Shallow-tagged field %s should share the same reference.", field.Name))
		switch field.TypeCategory {
		case types.CatMap:
			// Maps can only be compared to nil in Go, so verify via mutation.
			e.emitRaw(fmt.Sprintf("// Mutate original.%s and verify clone.%s is affected (same reference).", field.Name, field.Name))
			if isBuiltinPrimitive(field.ValueType) {
				e.emitRaw(fmt.Sprintf("original.%s[%s] = %s", field.Name, mapTestKey(field.KeyType), alternateMapValue(field.ValueType)))
				e.emitRaw(fmt.Sprintf("if clone.%s[%s] != %s {", field.Name, mapTestKey(field.KeyType), alternateMapValue(field.ValueType)))
				e.indent++
				e.emitRaw(fmt.Sprintf(`t.Error("%s (shallow) should share the same reference as the original")`, field.Name))
				e.indent--
				e.emitRaw("}")
			} else {
				// Non-primitive map values — check via length mutation.
				e.emitRaw(fmt.Sprintf("originalLen := len(original.%s)", field.Name))
				e.emitRaw(fmt.Sprintf("for k := range original.%s { original.%s[k] = %s{}; break }", field.Name, field.Name, field.ValueType))
				e.emitRaw(fmt.Sprintf("if len(clone.%s) != originalLen {", field.Name))
				e.indent++
				e.emitRaw(fmt.Sprintf(`t.Error("%s (shallow) should share the same reference as the original")`, field.Name))
				e.indent--
				e.emitRaw("}")
			}
		case types.CatSlice:
			// Slices can be compared with reflect.DeepEqual or by checking if header mutation affects both.
			e.emitRaw(fmt.Sprintf("// Mutate original.%s and verify clone.%s is affected (same reference).", field.Name, field.Name))
			if isBuiltinPrimitive(field.ElemType) {
				e.emitRaw(fmt.Sprintf("original.%s[0] = %s", field.Name, alternateSliceValue(field.ElemType)))
				e.emitRaw(fmt.Sprintf("if clone.%s[0] != %s {", field.Name, alternateSliceValue(field.ElemType)))
				e.indent++
				e.emitRaw(fmt.Sprintf(`t.Error("%s (shallow) should share the same reference as the original")`, field.Name))
				e.indent--
				e.emitRaw("}")
			} else {
				e.emitRaw(fmt.Sprintf("if &original.%s[0] != &clone.%s[0] {", field.Name, field.Name))
				e.indent++
				e.emitRaw(fmt.Sprintf(`t.Error("%s (shallow) should share the same backing array")`, field.Name))
				e.indent--
				e.emitRaw("}")
			}
		case types.CatPtrPrimitive, types.CatPtrStruct:
			e.emitRaw(fmt.Sprintf("if clone.%s != original.%s {", field.Name, field.Name))
			e.indent++
			e.emitRaw(fmt.Sprintf(`t.Error("%s (shallow) should share the same reference as the original")`, field.Name))
			e.indent--
			e.emitRaw("}")
		}
		e.emitBlankLine()
	}

	e.indent--
	e.emitRaw("}")
}

// -------------------------------------------- Empty-Field Test --------------------------------------------

func (e *testEmitter) emitEmptyTest(info *types.StructInfo) {
	e.emitRaw(fmt.Sprintf("func Test%s_Clone_EmptyFields(t *testing.T) {", utils.ToUpperAtN(0, info.Name)))
	e.indent++
	e.emitRaw("t.Parallel()")
	e.emitBlankLine()

	// Build original with non-empty values for empty-tagged fields.
	e.emitRaw(fmt.Sprintf("original := &%s{", info.Name))
	e.indent++
	for _, field := range info.Fields {
		if field.Directive.Empty && !isPrimitiveCategory(field.TypeCategory) {
			e.emitRaw(fmt.Sprintf("%s: %s,", field.Name, testFieldValue(field)))
		}
	}
	e.indent--
	e.emitRaw("}")

	e.emitBlankLine()
	e.emitRaw("clone, err := original.Clone()")
	e.emitRaw("if err != nil {")
	e.indent++
	e.emitRaw(`t.Fatalf("Clone() returned error: %v", err)`)
	e.indent--
	e.emitRaw("}")
	e.emitBlankLine()

	// Verify each empty-tagged container field is empty but non-nil.
	for _, field := range info.Fields {
		if !field.Directive.Empty || isPrimitiveCategory(field.TypeCategory) {
			continue
		}
		switch field.TypeCategory {
		case types.CatSlice:
			e.emitRaw(fmt.Sprintf("// Empty-tagged field %s should be non-nil with length 0.", field.Name))
			e.emitRaw(fmt.Sprintf("if clone.%s == nil {", field.Name))
			e.indent++
			e.emitRaw(fmt.Sprintf(`t.Error("%s (empty) should be non-nil")`, field.Name))
			e.indent--
			e.emitRaw("}")
			e.emitRaw(fmt.Sprintf("if len(clone.%s) != 0 {", field.Name))
			e.indent++
			e.emitRaw(fmt.Sprintf(`t.Errorf("empty field %s should have length 0, got %%d", len(clone.%s))`, field.Name, field.Name))
			e.indent--
			e.emitRaw("}")
		case types.CatMap:
			e.emitRaw(fmt.Sprintf("// Empty-tagged field %s should be non-nil with length 0.", field.Name))
			e.emitRaw(fmt.Sprintf("if clone.%s == nil {", field.Name))
			e.indent++
			e.emitRaw(fmt.Sprintf(`t.Error("%s (empty) should be non-nil")`, field.Name))
			e.indent--
			e.emitRaw("}")
			e.emitRaw(fmt.Sprintf("if len(clone.%s) != 0 {", field.Name))
			e.indent++
			e.emitRaw(fmt.Sprintf(`t.Errorf("empty field %s should have length 0, got %%d", len(clone.%s))`, field.Name, field.Name))
			e.indent--
			e.emitRaw("}")
		case types.CatPtrStruct, types.CatPtrPrimitive:
			e.emitRaw(fmt.Sprintf("// Empty-tagged field %s should be non-nil.", field.Name))
			e.emitRaw(fmt.Sprintf("if clone.%s == nil {", field.Name))
			e.indent++
			e.emitRaw(fmt.Sprintf(`t.Error("%s (empty) should be non-nil")`, field.Name))
			e.indent--
			e.emitRaw("}")
		case types.CatStruct:
			e.emitRaw(fmt.Sprintf("// Empty-tagged field %s should be zero-valued struct.", field.Name))
			e.emitRaw(fmt.Sprintf("if clone.%s != (%s{}) {", field.Name, field.Type))
			e.indent++
			e.emitRaw(fmt.Sprintf(`t.Errorf("empty field %s should be zero-valued struct")`, field.Name))
			e.indent--
			e.emitRaw("}")
		}
		e.emitBlankLine()
	}

	e.indent--
	e.emitRaw("}")
}

// -------------------------------------------- Clone-Tag Stub Test --------------------------------------------

// emitCloneTagStubTest emits a minimal test stub for structs that use the "clone" directive.
// Since the convention-based clone functions (e.g., CloneTypeNameField) are user-provided
// and may not exist yet, we emit a placeholder test with instructions rather than calling
// Clone() directly (which would fail to compile).
func (e *testEmitter) emitCloneTagStubTest(info *types.StructInfo) {
	e.emitRaw(fmt.Sprintf("func Test%s_Clone_Placeholder(t *testing.T) {", utils.ToUpperAtN(0, info.Name)))
	e.indent++
	e.emitRaw("t.Parallel()")
	e.emitBlankLine()

	// List the clone-tagged fields that need user-provided functions.
	var cloneFields []string
	for _, field := range info.Fields {
		if field.Directive.Clone {
			cloneFields = append(cloneFields, field.Name)
		}
	}

	e.emitComment(fmt.Sprintf("%s uses the 'clone' directive on field(s): %s.", info.Name, strings.Join(cloneFields, ", ")))
	e.emitComment("The generated Clone() method depends on convention-based clone functions that must be")
	e.emitComment("provided by the user. Once those functions are implemented, replace this placeholder")
	e.emitComment("with comprehensive tests for nil safety, round-trip, and deep-copy independence.")
	e.emitBlankLine()
	e.emitComment("Expected function signatures:")
	for _, field := range info.Fields {
		if field.Directive.Clone {
			fnName := fmt.Sprintf("Clone%s%s", info.Name, field.Name)
			e.emitComment(fmt.Sprintf("  %s(x.%s)", fnName, field.Name))
		}
	}
	e.emitBlankLine()
	e.emitRaw(`t.Skip("clone-tagged fields require user-provided convention functions")`)
	e.indent--
	e.emitRaw("}")
}

// -------------------------------------------- Field Value Generators --------------------------------------------

// testFieldValue returns a Go expression that creates a non-zero test value for the field.
func testFieldValue(field types.FieldInfo) string {
	if field.Directive.Skip || field.Directive.Shallow || field.Directive.Empty || field.Directive.Clone {
		// For skip/shallow/empty/clone fields, still generate a value so we can test them.
	}

	switch field.TypeCategory {
	case types.CatPrimitive:
		return primitiveTestValue(field.Type)
	case types.CatSlice:
		return sliceTestValue(field)
	case types.CatMap:
		return mapTestLiteral(field)
	case types.CatPtrPrimitive:
		return fmt.Sprintf("ptr(%s)", primitiveTestValue(field.PointedToType))
	case types.CatPtrStruct:
		return fmt.Sprintf("&%s{}", field.PointedToType)
	case types.CatStruct:
		return fmt.Sprintf("%s{}", field.Type)
	case types.CatInterface:
		return "nil"
	case types.CatUnknown:
		return "nil"
	default:
		return "nil"
	}
}

// primitiveTestValue returns a non-zero Go literal for a primitive type.
func primitiveTestValue(typeStr string) string {
	switch typeStr {
	case "string":
		return `"test"`
	case "bool":
		return "true"
	case "int":
		return "1"
	case "int8":
		return "int8(1)"
	case "int16":
		return "int16(1)"
	case "int32":
		return "int32(1)"
	case "int64":
		return "int64(1)"
	case "uint":
		return "uint(1)"
	case "uint8":
		return "uint8(1)"
	case "uint16":
		return "uint16(1)"
	case "uint32":
		return "uint32(1)"
	case "uint64":
		return "uint64(1)"
	case "float32":
		return "float32(1.0)"
	case "float64":
		return "1.0"
	case "byte":
		return "byte(1)"
	case "rune":
		return "rune(65)"
	case "complex64":
		return "complex64(1 + 0i)"
	case "complex128":
		return "complex128(1 + 0i)"
	case "uintptr":
		return "uintptr(1)"
	case "error":
		return `fmt.Errorf("test")`
	default:
		return `""`
	}
}

// sliceTestValue returns a Go literal for a non-empty slice.
func sliceTestValue(field types.FieldInfo) string {
	elem := field.ElemType
	if isBuiltinPrimitive(elem) {
		return fmt.Sprintf("%s{%s, %s}", field.Type, primitiveTestValue(elem), primitiveTestValueAlternate(elem))
	}
	// Struct element — use zero-value structs.
	return fmt.Sprintf("%s{{}, {}}", field.Type)
}

// mapTestLiteral returns a Go literal for a non-empty map.
func mapTestLiteral(field types.FieldInfo) string {
	key := field.KeyType
	val := field.ValueType
	return fmt.Sprintf("%s{%s: %s}", field.Type, mapTestKey(key), mapTestValueLiteral(val))
}

// mapTestKey returns a Go expression for a test map key.
func mapTestKey(keyType string) string {
	if isBuiltinPrimitive(keyType) {
		v := primitiveTestValue(keyType)
		// For string keys, use a shorter value.
		if keyType == "string" {
			return `"k"`
		}
		return v
	}
	return fmt.Sprintf("%s{}", keyType)
}

// mapTestValueLiteral returns a Go expression for a test map value.
func mapTestValueLiteral(valType string) string {
	if isBuiltinPrimitive(valType) {
		return primitiveTestValue(valType)
	}
	return fmt.Sprintf("%s{}", valType)
}

// alternateSliceValue returns a different Go literal than testFieldValue for the element type,
// used to mutate the original and verify the clone is independent.
func alternateSliceValue(elemType string) string {
	switch elemType {
	case "string":
		return `"modified"`
	case "bool":
		return "false"
	case "int", "int8", "int16", "int32", "int64":
		return "999"
	case "uint", "uint8", "uint16", "uint32", "uint64":
		return "999"
	case "float32", "float64":
		return "999.0"
	case "byte":
		return "byte(99)"
	case "rune":
		return "rune(90)"
	default:
		return `"modified"`
	}
}

// alternateMapValue returns a different Go literal for the value type.
func alternateMapValue(valType string) string {
	return alternateSliceValue(valType)
}

// primitiveTestValueAlternate returns a second, different non-zero Go literal for a primitive type.
func primitiveTestValueAlternate(typeStr string) string {
	switch typeStr {
	case "string":
		return `"other"`
	case "bool":
		return "false"
	case "int":
		return "2"
	case "int8":
		return "int8(2)"
	case "int16":
		return "int16(2)"
	case "int32":
		return "int32(2)"
	case "int64":
		return "int64(2)"
	case "uint":
		return "uint(2)"
	case "uint8":
		return "uint8(2)"
	case "uint16":
		return "uint16(2)"
	case "uint32":
		return "uint32(2)"
	case "uint64":
		return "uint64(2)"
	case "float32":
		return "float32(2.0)"
	case "float64":
		return "2.0"
	case "byte":
		return "byte(2)"
	case "rune":
		return "rune(66)"
	default:
		return `"other"`
	}
}

// zeroValue returns a Go expression representing the zero value for the field's type.
func zeroValue(field types.FieldInfo) string {
	switch field.TypeCategory {
	case types.CatPrimitive:
		return primitiveZeroValue(field.Type)
	case types.CatSlice, types.CatMap:
		return "nil"
	case types.CatPtrPrimitive, types.CatPtrStruct:
		return "nil"
	case types.CatStruct:
		return fmt.Sprintf("%s{}", field.Type)
	case types.CatInterface:
		return "nil"
	default:
		return "nil"
	}
}

// primitiveZeroValue returns a Go expression for the zero value of a primitive type.
func primitiveZeroValue(typeStr string) string {
	switch typeStr {
	case "string":
		return `""`
	case "bool":
		return "false"
	case "int":
		return "0"
	case "int8":
		return "int8(0)"
	case "int16":
		return "int16(0)"
	case "int32":
		return "int32(0)"
	case "int64":
		return "int64(0)"
	case "uint":
		return "uint(0)"
	case "uint8":
		return "uint8(0)"
	case "uint16":
		return "uint16(0)"
	case "uint32":
		return "uint32(0)"
	case "uint64":
		return "uint64(0)"
	case "float32":
		return "float32(0)"
	case "float64":
		return "0.0"
	case "byte":
		return "byte(0)"
	case "rune":
		return "rune(0)"
	default:
		return `""`
	}
}

// -------------------------------------------- Field Category Predicates --------------------------------------------

// hasPtrPrimitiveFields reports whether the struct has any pointer-to-primitive fields.
func (e *testEmitter) hasPtrPrimitiveFields(info *types.StructInfo) bool {
	for _, field := range info.Fields {
		if field.TypeCategory == types.CatPtrPrimitive {
			return true
		}
	}
	return false
}

// hasDeepContainerFields reports whether the struct has any deep-copied container fields
// (slices, maps, pointers) where independence should be verified.
func (e *testEmitter) hasDeepContainerFields(info *types.StructInfo) bool {
	for _, field := range info.Fields {
		if isDeepCopiedContainer(field) {
			return true
		}
	}
	return false
}

// hasSkipFields reports whether the struct has any skip-tagged fields.
func (e *testEmitter) hasSkipFields(info *types.StructInfo) bool {
	for _, field := range info.Fields {
		if field.Directive.Skip {
			return true
		}
	}
	return false
}

// hasShallowContainerFields reports whether the struct has any shallow-tagged container fields.
func (e *testEmitter) hasShallowContainerFields(info *types.StructInfo) bool {
	for _, field := range info.Fields {
		if field.Directive.Shallow && isContainerType(field.TypeCategory) {
			return true
		}
	}
	return false
}

// hasEmptyFields reports whether the struct has any empty-tagged non-primitive fields.
func (e *testEmitter) hasEmptyFields(info *types.StructInfo) bool {
	for _, field := range info.Fields {
		if field.Directive.Empty && !isPrimitiveCategory(field.TypeCategory) {
			return true
		}
	}
	return false
}

// hasCloneTagFields reports whether the struct has any clone-tagged fields.
func (e *testEmitter) hasCloneTagFields(info *types.StructInfo) bool {
	for _, field := range info.Fields {
		if field.Directive.Clone {
			return true
		}
	}
	return false
}

// isDeepCopiedContainer reports whether a field is a deep-copied container
// (slice, map, or pointer) where the clone should be independent of the original.
func isDeepCopiedContainer(field types.FieldInfo) bool {
	if field.Directive.Skip || field.Directive.Shallow || field.Directive.Empty || field.Directive.Clone {
		return false
	}
	switch field.TypeCategory {
	case types.CatSlice, types.CatMap, types.CatPtrPrimitive, types.CatPtrStruct, types.CatStruct:
		return true
	}
	return false
}

// isContainerType reports whether the type category is a container (slice, map, pointer).
func isContainerType(cat types.TypeCategory) bool {
	switch cat {
	case types.CatSlice, types.CatMap, types.CatPtrPrimitive, types.CatPtrStruct:
		return true
	}
	return false
}

// -------------------------------------------- Output Helpers --------------------------------------------

func (e *testEmitter) emitRaw(s string) {
	e.buf.WriteString(strings.Repeat("\t", e.indent))
	e.buf.WriteString(s)
	e.buf.WriteString("\n")
}

func (e *testEmitter) emitBlankLine() {
	e.buf.WriteString("\n")
}

func (e *testEmitter) emitComment(s string) {
	e.emitRaw("// " + s)
}
