// Package emitter. testgen.go - Generates Go test files for Clone() method implementations
// produced by doppelgen. Each generated test file exercises the clone method with nil guards,
// reflect-based deep equality checks, mutation independence verification per field directive,
// skip-field zero-value assertions, shallow-field reference sharing, and empty-field non-nil checks.
package emitter

import (
	"bytes"
	"fmt"
	"sort"
	"strings"

	"github.com/seyallius/doppel/cmd/doppelgen/internal/types"
	"github.com/seyallius/doppel/cmd/doppelgen/pkg/utils"
	"golang.org/x/tools/imports"
)

//fixme(type-alias-testgen): Skip fields that have type alias for map or slice entirely in tests.

// -------------------------------------------- Types --------------------------------------------

// testEmitter holds state for a single test-file generation run.
type testEmitter struct {
	buf     bytes.Buffer
	imports map[string]types.ImportSpec
	indent  int
}

// -------------------------------------------- Public API --------------------------------------------

// GenerateTest produces the complete Go test file content for a generated Clone() method.
// It creates focused sub-tests that verify:
//   - nil safety
//   - reflect.DeepEqual round-trip (clone has same values as original)
//   - mutation independence (mutating clone does not affect original, and vice versa)
//   - skip-field zero values
//   - shallow-field reference sharing
//   - empty-field non-nil semantics
//
// Returns an error if formatting fails.
func GenerateTest(structInfo *types.StructInfo) (string, error) {
	e := &testEmitter{
		buf:     bytes.Buffer{},
		indent:  0,
		imports: make(map[string]types.ImportSpec),
	}

	e.emitHeader(structInfo)
	e.emitBlankLine()
	e.emitPackage(structInfo.Package)
	e.emitBlankLine()
	e.emitImports(structInfo)
	e.emitBlankLine()

	// Emit the ptr helper if there are pointer-to-primitive fields.
	if e.hasPtrPrimitiveFields(structInfo) {
		e.emitPtrHelper()
		e.emitBlankLine()
	}

	// Structs with "clone"-tagged fields depend on convention-based functions
	// that may not exist yet. Emit a notice and a stub test instead of full tests.
	if e.hasCloneTagFields(structInfo) {
		e.emitCloneTagStubTest(structInfo)
	} else {
		// 1. Nil safety.
		e.emitNilTest(structInfo)
		e.emitBlankLine()

		// 2. reflect.DeepEqual round-trip — clone must have identical values to original.
		e.emitDeepEqualTest(structInfo)

		// 3. Mutation independence — mutate clone fields and verify original is unaffected,
		//    then mutate original fields and verify clone is unaffected.
		//    Only emitted when the struct has deep-copied container fields.
		if e.hasDeepContainerFields(structInfo) {
			e.emitBlankLine()
			e.emitMutationIndependenceTest(structInfo)
		}

		// 4. Skip-field zero values.
		if e.hasSkipFields(structInfo) {
			e.emitBlankLine()
			e.emitSkipTest(structInfo)
		}

		// 5. Shallow-field reference sharing.
		if e.hasShallowContainerFields(structInfo) {
			e.emitBlankLine()
			e.emitShallowTest(structInfo)
		}

		// 6. Empty-field non-nil assertions.
		if e.hasEmptyFields(structInfo) {
			e.emitBlankLine()
			e.emitEmptyTest(structInfo)
		}
	}

	// Format the generated source.
	raw := strings.TrimSpace(e.buf.String()) + "\n"
	formatted, err := imports.Process(structInfo.File, []byte(raw), nil)
	if err != nil {
		return raw, fmt.Errorf("format test code for %s: %w", structInfo.Name, err)
	}

	return string(formatted), nil
}

// -------------------------------------------- Internal Helpers --------------------------------------------

// -------------------------------------------- Header & Package --------------------------------------------

func (e *testEmitter) emitHeader(info *types.StructInfo) {
	e.emitComment("Code generated by doppelgen. DO NOT EDIT.")
	e.emitComment(fmt.Sprintf("Source: %s", info.File))
}

func (e *testEmitter) emitPackage(name string) {
	e.emitRaw(fmt.Sprintf("package %s", name))
}

// -------------------------------------------- Imports --------------------------------------------

func (e *testEmitter) emitImports(info *types.StructInfo) {
	// Test files always need "testing" and "reflect" for DeepEqual checks.
	e.imports["testing"] = types.ImportSpec{Path: "testing"}
	e.imports["reflect"] = types.ImportSpec{Path: "reflect"}

	_ = info

	if len(e.imports) == 0 {
		return
	}

	e.emitRaw("import (")
	e.indent++

	var paths []string
	for path := range e.imports {
		paths = append(paths, path)
	}
	sort.Strings(paths)

	for _, path := range paths {
		e.emitRaw(fmt.Sprintf(`"%s"`, path))
	}

	e.indent--
	e.emitRaw(")")
}

// -------------------------------------------- ptr Helper --------------------------------------------

// emitPtrHelper emits a generic pointer constructor used in tests:
//
//	func ptr[T any](v T) *T { return &v }
func (e *testEmitter) emitPtrHelper() {
	e.emitRaw("func ptr[T any](v T) *T { return &v }")
}

// -------------------------------------------- Nil Test --------------------------------------------

func (e *testEmitter) emitNilTest(info *types.StructInfo) {
	e.emitRaw(fmt.Sprintf("func Test%s_Clone_Nil(t *testing.T) {", utils.ToUpperAtN(0, info.Name)))
	e.indent++
	e.emitRaw("t.Parallel()")
	e.emitBlankLine()
	e.emitRaw(fmt.Sprintf("var x *%s = nil", info.Name))
	e.emitRaw("got, err := x.Clone()")
	e.emitRaw("if err != nil {")
	e.indent++
	e.emitRaw(`t.Fatalf("Clone() returned error: %v", err)`)
	e.indent--
	e.emitRaw("}")
	e.emitRaw("if got != nil {")
	e.indent++
	e.emitRaw(`t.Error("Clone() of nil should return nil")`)
	e.indent--
	e.emitRaw("}")
	e.indent--
	e.emitRaw("}")
}

// -------------------------------------------- reflect.DeepEqual Round-Trip Test --------------------------------------------

// emitDeepEqualTest emits a test that:
//  1. Constructs an original with non-zero values.
//  2. Clones it.
//  3. Checks clone != nil and clone != original (pointer inequality).
//  4. Uses reflect.DeepEqual to verify every non-skip field has the same value.
//  5. Verifies skip fields are zero-valued in the clone.
func (e *testEmitter) emitDeepEqualTest(info *types.StructInfo) {
	e.emitRaw(fmt.Sprintf("func Test%s_Clone_DeepEqual(t *testing.T) {", utils.ToUpperAtN(0, info.Name)))
	e.indent++
	e.emitRaw("t.Parallel()")
	e.emitBlankLine()

	// Construct original with non-zero values for all fields.
	e.emitComment("Construct original with non-zero test values.")
	e.emitRaw(fmt.Sprintf("original := &%s{", info.Name))
	e.indent++
	for _, field := range info.Fields {
		e.emitRaw(fmt.Sprintf("%s: %s,", field.Name, testFieldValue(field)))
	}
	e.indent--
	e.emitRaw("}")

	e.emitBlankLine()
	e.emitRaw("clone, err := original.Clone()")
	e.emitRaw("if err != nil {")
	e.indent++
	e.emitRaw(`t.Fatalf("Clone() returned error: %v", err)`)
	e.indent--
	e.emitRaw("}")

	e.emitBlankLine()
	e.emitComment("Basic pointer invariants.")
	e.emitRaw("if clone == nil {")
	e.indent++
	e.emitRaw(`t.Fatal("Clone() returned nil for non-nil input")`)
	e.indent--
	e.emitRaw("}")
	e.emitRaw("if clone == original {")
	e.indent++
	e.emitRaw(`t.Error("Clone() returned the same pointer as original")`)
	e.indent--
	e.emitRaw("}")

	e.emitBlankLine()
	e.emitComment("reflect.DeepEqual check — every non-skip field must have the same value.")

	for _, field := range info.Fields {
		if field.Directive.Skip {
			// Skip fields must be zero in the clone — verified in emitSkipTest.
			continue
		}
		if field.Directive.Empty {
			// Empty fields have a different (empty) value by design — verified in emitEmptyTest.
			continue
		}
		e.emitRaw(fmt.Sprintf("if !reflect.DeepEqual(clone.%s, original.%s) {", field.Name, field.Name))
		e.indent++
		e.emitRaw(fmt.Sprintf(`t.Errorf("field %s: got %%v, want %%v", clone.%s, original.%s)`, field.Name, field.Name, field.Name))
		e.indent--
		e.emitRaw("}")
	}

	e.indent--
	e.emitRaw("}")
}

// -------------------------------------------- Mutation Independence Test --------------------------------------------

// emitMutationIndependenceTest emits a test that verifies deep-copied fields are truly independent.
// For each deep container field it:
//  1. Builds an original with non-zero values.
//  2. Clones it.
//  3. Mutates the CLONE's field — verifies original is unchanged.
//  4. Resets state (re-clone from fresh original), mutates the ORIGINAL's field — verifies clone is unchanged.
//
// This catches bugs where Clone() returns a shallow copy that shares backing memory.
func (e *testEmitter) emitMutationIndependenceTest(info *types.StructInfo) {
	e.emitRaw(fmt.Sprintf("func Test%s_Clone_MutationIndependence(t *testing.T) {", utils.ToUpperAtN(0, info.Name)))
	e.indent++
	e.emitRaw("t.Parallel()")
	e.emitBlankLine()

	for _, field := range info.Fields {
		if !isDeepCopiedContainer(field) {
			continue
		}

		// Emit a sub-test per field for clear failure messages.
		e.emitRaw(fmt.Sprintf(`t.Run("%s", func(t *testing.T) {`, field.Name))
		e.indent++
		e.emitRaw("t.Parallel()")
		e.emitBlankLine()

		e.emitMutationSubTest(field, info.Name)

		e.indent--
		e.emitRaw("})")
		e.emitBlankLine()
	}

	e.indent--
	e.emitRaw("}")
}

// emitMutationSubTest emits the body of a per-field mutation independence sub-test.
// It always emits two directions:
//   - mutate clone → original should be unchanged
//   - mutate original → clone should be unchanged
func (e *testEmitter) emitMutationSubTest(field types.FieldInfo, structName string) {
	// Helper: build original literal with just this field populated.
	buildOriginal := func(structName string) {
		e.emitRaw(fmt.Sprintf("original := &%s{", structName))
		e.indent++
		e.emitRaw(fmt.Sprintf("%s: %s,", field.Name, testFieldValue(field)))
		e.indent--
		e.emitRaw("}")
	}

	clone := func() {
		e.emitRaw("clone, err := original.Clone()")
		e.emitRaw("if err != nil {")
		e.indent++
		e.emitRaw(`t.Fatalf("Clone() returned error: %v", err)`)
		e.indent--
		e.emitRaw("}")
		e.emitRaw("if clone == nil {")
		e.indent++
		e.emitRaw(`t.Fatal("Clone() returned nil")`)
		e.indent--
		e.emitRaw("}")
	}

	switch field.TypeCategory {
	case types.CatSlice:
		if isBuiltinPrimitive(field.ElemType) {
			// --- Direction 1: mutate clone → original unchanged ---
			e.emitRaw("{") // Start block scope for direction 1
			e.indent++
			e.emitComment("Direction 1: mutate clone's slice → original must be unaffected.")
			buildOriginal(structName)
			clone()
			e.emitRaw(fmt.Sprintf("beforeOriginal := original.%s[0]", field.Name))
			e.emitRaw(fmt.Sprintf("clone.%s[0] = %s", field.Name, alternateSliceValue(field.ElemType)))
			e.emitRaw(fmt.Sprintf("if !reflect.DeepEqual(original.%s[0], beforeOriginal) {", field.Name))
			e.indent++
			e.emitRaw(fmt.Sprintf(`t.Errorf("field %s: mutating clone affected original: got %%v, want %%v", original.%s[0], beforeOriginal)`, field.Name, field.Name))
			e.indent--
			e.emitRaw("}")
			e.indent--
			e.emitRaw("}") // End block scope for direction 1
			e.emitBlankLine()

			// --- Direction 2: mutate original → clone unchanged ---
			e.emitRaw("{") // Start block scope for direction 2
			e.indent++
			e.emitComment("Direction 2: mutate original's slice → clone must be unaffected.")
			buildOriginal(structName)
			clone()
			e.emitRaw(fmt.Sprintf("beforeClone := clone.%s[0]", field.Name))
			e.emitRaw(fmt.Sprintf("original.%s[0] = %s", field.Name, alternateSliceValue(field.ElemType)))
			e.emitRaw(fmt.Sprintf("if !reflect.DeepEqual(clone.%s[0], beforeClone) {", field.Name))
			e.indent++
			e.emitRaw(fmt.Sprintf(`t.Errorf("field %s: mutating original affected clone: got %%v, want %%v", clone.%s[0], beforeClone)`, field.Name, field.Name))
			e.indent--
			e.emitRaw("}")
			e.indent--
			e.emitRaw("}") // End block scope for direction 2
		} else {
			// Non-primitive slice: verify backing array pointers differ.
			e.emitComment("Struct-element slice: verify backing array is independent (different pointer).")
			buildOriginal(structName)
			clone()
			e.emitRaw(fmt.Sprintf("if len(original.%s) > 0 && len(clone.%s) > 0 && &original.%s[0] == &clone.%s[0] {", field.Name, field.Name, field.Name, field.Name))
			e.indent++
			e.emitRaw(fmt.Sprintf(`t.Errorf("field %s: clone shares backing array with original")`, field.Name))
			e.indent--
			e.emitRaw("}")
		}

	case types.CatMap:
		if isBuiltinPrimitive(field.ValueType) {
			mutKey := mapTestKey(field.KeyType)
			mutVal := alternateMapValue(field.ValueType)

			// --- Direction 1: mutate clone → original unchanged ---
			e.emitRaw("{")
			e.indent++
			e.emitComment("Direction 1: mutate clone's map → original must be unaffected.")
			buildOriginal(structName)
			clone()
			e.emitRaw(fmt.Sprintf("beforeOriginal := original.%s[%s]", field.Name, mutKey))
			e.emitRaw(fmt.Sprintf("clone.%s[%s] = %s", field.Name, mutKey, mutVal))
			e.emitRaw(fmt.Sprintf("if !reflect.DeepEqual(original.%s[%s], beforeOriginal) {", field.Name, mutKey))
			e.indent++
			e.emitRaw(fmt.Sprintf(`t.Errorf("field %s: mutating clone affected original: got %%v, want %%v", original.%s[%s], beforeOriginal)`, field.Name, field.Name, mutKey))
			e.indent--
			e.emitRaw("}")
			e.indent--
			e.emitRaw("}")
			e.emitBlankLine()

			// --- Direction 2: mutate original → clone unchanged ---
			e.emitRaw("{")
			e.indent++
			e.emitComment("Direction 2: mutate original's map → clone must be unaffected.")
			buildOriginal(structName)
			clone()
			e.emitRaw(fmt.Sprintf("beforeClone := clone.%s[%s]", field.Name, mutKey))
			e.emitRaw(fmt.Sprintf("original.%s[%s] = %s", field.Name, mutKey, mutVal))
			e.emitRaw(fmt.Sprintf("if !reflect.DeepEqual(clone.%s[%s], beforeClone) {", field.Name, mutKey))
			e.indent++
			e.emitRaw(fmt.Sprintf(`t.Errorf("field %s: mutating original affected clone: got %%v, want %%v", clone.%s[%s], beforeClone)`, field.Name, field.Name, mutKey))
			e.indent--
			e.emitRaw("}")
			e.indent--
			e.emitRaw("}")
		} else {
			// Struct-value map: verify the map headers are different objects by adding a new key.
			newKey := mapTestKey(field.KeyType)
			e.emitComment("Struct-value map: verify the two maps are independent (new key inserted in clone must not appear in original).")
			buildOriginal(structName)
			clone()
			e.emitRaw(fmt.Sprintf("clone.%s[%s] = %s{}", field.Name, newKey, field.ValueType))
			e.emitRaw(fmt.Sprintf("if _, ok := original.%s[%s]; ok {", field.Name, newKey))
			e.indent++
			e.emitRaw(fmt.Sprintf(`t.Errorf("field %s: new key inserted in clone appeared in original")`, field.Name))
			e.indent--
			e.emitRaw("}")
		}

	case types.CatPtrPrimitive:
		origVal := primitiveTestValue(field.PointedToType)
		altVal := alternateSliceValue(field.PointedToType)

		// --- Direction 1: mutate clone → original unchanged ---
		e.emitRaw("{")
		e.indent++
		e.emitComment("Direction 1: mutate value through clone's pointer → original's pointed-to value must be unaffected.")
		buildOriginal(structName)
		clone()
		e.emitRaw(fmt.Sprintf("if original.%s != nil && clone.%s != nil {", field.Name, field.Name))
		e.indent++
		e.emitRaw(fmt.Sprintf("beforeOriginal := *original.%s", field.Name))
		e.emitRaw(fmt.Sprintf("*clone.%s = %s", field.Name, altVal))
		e.emitRaw(fmt.Sprintf("if !reflect.DeepEqual(*original.%s, beforeOriginal) {", field.Name))
		e.indent++
		e.emitRaw(fmt.Sprintf(`t.Errorf("field %s: mutating clone affected original: got %%v, want %%v", *original.%s, beforeOriginal)`, field.Name, field.Name))
		e.indent--
		e.emitRaw("}")
		e.indent--
		e.emitRaw("}")
		e.indent--
		e.emitRaw("}")
		e.emitBlankLine()

		// --- Direction 2: mutate original → clone unchanged ---
		e.emitRaw("{")
		e.indent++
		e.emitComment("Direction 2: mutate value through original's pointer → clone's pointed-to value must be unaffected.")
		buildOriginal(structName)
		clone()
		e.emitRaw(fmt.Sprintf("if original.%s != nil && clone.%s != nil {", field.Name, field.Name))
		e.indent++
		e.emitRaw(fmt.Sprintf("beforeClone := *clone.%s", field.Name))
		e.emitRaw(fmt.Sprintf("*original.%s = %s", field.Name, origVal))
		e.emitRaw(fmt.Sprintf("if !reflect.DeepEqual(*clone.%s, beforeClone) {", field.Name))
		e.indent++
		e.emitRaw(fmt.Sprintf(`t.Errorf("field %s: mutating original affected clone: got %%v, want %%v", *clone.%s, beforeClone)`, field.Name, field.Name))
		e.indent--
		e.emitRaw("}")
		e.indent--
		e.emitRaw("}")
		e.indent--
		e.emitRaw("}")

	case types.CatPtrStruct:
		// Pointer equality check — the two pointers must differ.
		e.emitComment("Pointer-to-struct: the clone and original must point to different structs.")
		buildOriginal(structName)
		clone()
		e.emitRaw(fmt.Sprintf("if original.%s != nil && clone.%s != nil && original.%s == clone.%s {", field.Name, field.Name, field.Name, field.Name))
		e.indent++
		e.emitRaw(fmt.Sprintf(`t.Errorf("field %s: clone and original share the same pointer")`, field.Name))
		e.indent--
		e.emitRaw("}")

	case types.CatStruct:
		// Value struct: addresses must differ.
		e.emitComment("Value struct: verify deep copies are independent by address.")
		buildOriginal(structName)
		clone()
		e.emitRaw(fmt.Sprintf("if &original.%s == &clone.%s {", field.Name, field.Name))
		e.indent++
		e.emitRaw(fmt.Sprintf(`t.Errorf("field %s: clone and original share the same struct address")`, field.Name))
		e.indent--
		e.emitRaw("}")
	}
}

// -------------------------------------------- Skip-Field Test --------------------------------------------

func (e *testEmitter) emitSkipTest(info *types.StructInfo) {
	e.emitRaw(fmt.Sprintf("func Test%s_Clone_SkipFields(t *testing.T) {", utils.ToUpperAtN(0, info.Name)))
	e.indent++
	e.emitRaw("t.Parallel()")
	e.emitBlankLine()

	e.emitComment("Build original with non-zero values for skip-tagged fields.")
	e.emitRaw(fmt.Sprintf("original := &%s{", info.Name))
	e.indent++
	for _, field := range info.Fields {
		if field.Directive.Skip {
			e.emitRaw(fmt.Sprintf("%s: %s,", field.Name, testFieldValue(field)))
		}
	}
	e.indent--
	e.emitRaw("}")

	e.emitBlankLine()
	e.emitRaw("clone, err := original.Clone()")
	e.emitRaw("if err != nil {")
	e.indent++
	e.emitRaw(`t.Fatalf("Clone() returned error: %v", err)`)
	e.indent--
	e.emitRaw("}")
	e.emitBlankLine()

	for _, field := range info.Fields {
		if !field.Directive.Skip {
			continue
		}
		e.emitComment(fmt.Sprintf("Skip-tagged field %s must be zero-valued in the clone.", field.Name))
		zeroVal := zeroValue(field)
		if field.TypeCategory == types.CatStruct {
			// Structs: use reflect.DeepEqual against zero literal for comparability.
			e.emitRaw(fmt.Sprintf("if !reflect.DeepEqual(clone.%s, %s) {", field.Name, zeroVal))
		} else {
			e.emitRaw(fmt.Sprintf("if clone.%s != %s {", field.Name, zeroVal))
		}
		e.indent++
		e.emitRaw(fmt.Sprintf(`t.Errorf("skip field %s = %%v, want zero value", clone.%s)`, field.Name, field.Name))
		e.indent--
		e.emitRaw("}")
		e.emitBlankLine()
	}

	e.indent--
	e.emitRaw("}")
}

// -------------------------------------------- Shallow-Field Test --------------------------------------------

func (e *testEmitter) emitShallowTest(info *types.StructInfo) {
	e.emitRaw(fmt.Sprintf("func Test%s_Clone_ShallowFields(t *testing.T) {", utils.ToUpperAtN(0, info.Name)))
	e.indent++
	e.emitRaw("t.Parallel()")
	e.emitBlankLine()

	e.emitComment("Build original with non-zero shallow container fields.")
	e.emitRaw(fmt.Sprintf("original := &%s{", info.Name))
	e.indent++
	for _, field := range info.Fields {
		if field.Directive.Shallow && isContainerType(field.TypeCategory) {
			e.emitRaw(fmt.Sprintf("%s: %s,", field.Name, testFieldValue(field)))
		}
	}
	e.indent--
	e.emitRaw("}")

	e.emitBlankLine()
	e.emitRaw("clone, err := original.Clone()")
	e.emitRaw("if err != nil {")
	e.indent++
	e.emitRaw(`t.Fatalf("Clone() returned error: %v", err)`)
	e.indent--
	e.emitRaw("}")
	e.emitBlankLine()

	for _, field := range info.Fields {
		if !field.Directive.Shallow || !isContainerType(field.TypeCategory) {
			continue
		}
		e.emitComment(fmt.Sprintf("Shallow-tagged field %s: mutation of original must be visible in clone (shared reference).", field.Name))
		switch field.TypeCategory {
		case types.CatSlice:
			if isBuiltinPrimitive(field.ElemType) {
				e.emitRaw(fmt.Sprintf("original.%s[0] = %s", field.Name, alternateSliceValue(field.ElemType)))
				e.emitRaw(fmt.Sprintf("if !reflect.DeepEqual(clone.%s[0], original.%s[0]) {", field.Name, field.Name))
				e.indent++
				e.emitRaw(fmt.Sprintf(`t.Errorf("shallow field %s: clone did not reflect original mutation — expected shared reference")`, field.Name))
				e.indent--
				e.emitRaw("}")
			} else {
				e.emitRaw(fmt.Sprintf("if len(original.%s) > 0 && &original.%s[0] != &clone.%s[0] {", field.Name, field.Name, field.Name))
				e.indent++
				e.emitRaw(fmt.Sprintf(`t.Errorf("shallow field %s: clone does not share backing array with original")`, field.Name))
				e.indent--
				e.emitRaw("}")
			}
		case types.CatMap:
			if isBuiltinPrimitive(field.ValueType) {
				e.emitRaw(fmt.Sprintf("original.%s[%s] = %s", field.Name, mapTestKey(field.KeyType), alternateMapValue(field.ValueType)))
				e.emitRaw(fmt.Sprintf("if !reflect.DeepEqual(clone.%s[%s], original.%s[%s]) {", field.Name, mapTestKey(field.KeyType), field.Name, mapTestKey(field.KeyType)))
				e.indent++
				e.emitRaw(fmt.Sprintf(`t.Errorf("shallow field %s: clone did not reflect original map mutation — expected shared reference")`, field.Name))
				e.indent--
				e.emitRaw("}")
			} else {
				e.emitRaw(fmt.Sprintf("originalLen := len(original.%s)", field.Name))
				e.emitRaw(fmt.Sprintf("for k := range original.%s { original.%s[k] = %s{}; break }", field.Name, field.Name, field.ValueType))
				e.emitRaw(fmt.Sprintf("if len(clone.%s) != originalLen {", field.Name))
				e.indent++
				e.emitRaw(fmt.Sprintf(`t.Errorf("shallow field %s: clone does not share map reference with original")`, field.Name))
				e.indent--
				e.emitRaw("}")
			}
		case types.CatPtrPrimitive, types.CatPtrStruct:
			// Pointer equality: both must point to the exact same object.
			e.emitRaw(fmt.Sprintf("if clone.%s != original.%s {", field.Name, field.Name))
			e.indent++
			e.emitRaw(fmt.Sprintf(`t.Errorf("shallow field %s: clone pointer %%p != original pointer %%p", clone.%s, original.%s)`, field.Name, field.Name, field.Name))
			e.indent--
			e.emitRaw("}")
		}
		e.emitBlankLine()
	}

	e.indent--
	e.emitRaw("}")
}

// -------------------------------------------- Empty-Field Test --------------------------------------------

func (e *testEmitter) emitEmptyTest(info *types.StructInfo) {
	e.emitRaw(fmt.Sprintf("func Test%s_Clone_EmptyFields(t *testing.T) {", utils.ToUpperAtN(0, info.Name)))
	e.indent++
	e.emitRaw("t.Parallel()")
	e.emitBlankLine()

	e.emitComment("Build original with non-empty values for empty-tagged fields.")
	e.emitRaw(fmt.Sprintf("original := &%s{", info.Name))
	e.indent++
	for _, field := range info.Fields {
		if field.Directive.Empty && !isPrimitiveCategory(field.TypeCategory) {
			e.emitRaw(fmt.Sprintf("%s: %s,", field.Name, testFieldValue(field)))
		}
	}
	e.indent--
	e.emitRaw("}")

	e.emitBlankLine()
	e.emitRaw("clone, err := original.Clone()")
	e.emitRaw("if err != nil {")
	e.indent++
	e.emitRaw(`t.Fatalf("Clone() returned error: %v", err)`)
	e.indent--
	e.emitRaw("}")
	e.emitBlankLine()

	for _, field := range info.Fields {
		if !field.Directive.Empty || isPrimitiveCategory(field.TypeCategory) {
			continue
		}
		switch field.TypeCategory {
		case types.CatSlice:
			e.emitComment(fmt.Sprintf("Empty-tagged field %s: clone must be non-nil with length 0.", field.Name))
			e.emitRaw(fmt.Sprintf("if clone.%s == nil {", field.Name))
			e.indent++
			e.emitRaw(fmt.Sprintf(`t.Errorf("empty field %s: clone is nil, want non-nil empty slice")`, field.Name))
			e.indent--
			e.emitRaw("}")
			e.emitRaw(fmt.Sprintf("if len(clone.%s) != 0 {", field.Name))
			e.indent++
			e.emitRaw(fmt.Sprintf(`t.Errorf("empty field %s: clone has length %%d, want 0", len(clone.%s))`, field.Name, field.Name))
			e.indent--
			e.emitRaw("}")
		case types.CatMap:
			e.emitComment(fmt.Sprintf("Empty-tagged field %s: clone must be non-nil with length 0.", field.Name))
			e.emitRaw(fmt.Sprintf("if clone.%s == nil {", field.Name))
			e.indent++
			e.emitRaw(fmt.Sprintf(`t.Errorf("empty field %s: clone is nil, want non-nil empty map")`, field.Name))
			e.indent--
			e.emitRaw("}")
			e.emitRaw(fmt.Sprintf("if len(clone.%s) != 0 {", field.Name))
			e.indent++
			e.emitRaw(fmt.Sprintf(`t.Errorf("empty field %s: clone has length %%d, want 0", len(clone.%s))`, field.Name, field.Name))
			e.indent--
			e.emitRaw("}")
		case types.CatPtrStruct, types.CatPtrPrimitive:
			e.emitComment(fmt.Sprintf("Empty-tagged field %s: clone must be non-nil.", field.Name))
			e.emitRaw(fmt.Sprintf("if clone.%s == nil {", field.Name))
			e.indent++
			e.emitRaw(fmt.Sprintf(`t.Errorf("empty field %s: clone is nil, want non-nil empty pointer")`, field.Name))
			e.indent--
			e.emitRaw("}")
		case types.CatStruct:
			e.emitComment(fmt.Sprintf("Empty-tagged field %s: clone must be zero-valued struct.", field.Name))
			e.emitRaw(fmt.Sprintf("if !reflect.DeepEqual(clone.%s, (%s{})) {", field.Name, field.Type))
			e.indent++
			e.emitRaw(fmt.Sprintf(`t.Errorf("empty field %s: clone = %%v, want zero struct", clone.%s)`, field.Name, field.Name))
			e.indent--
			e.emitRaw("}")
		}
		e.emitBlankLine()
	}

	e.indent--
	e.emitRaw("}")
}

// -------------------------------------------- Clone-Tag Stub Test --------------------------------------------

// emitCloneTagStubTest emits a minimal test stub for structs that use the "clone" directive.
func (e *testEmitter) emitCloneTagStubTest(info *types.StructInfo) {
	e.emitRaw(fmt.Sprintf("func Test%s_Clone_Placeholder(t *testing.T) {", utils.ToUpperAtN(0, info.Name)))
	e.indent++
	e.emitRaw("t.Parallel()")
	e.emitBlankLine()

	var cloneFields []string
	for _, field := range info.Fields {
		if field.Directive.Clone {
			cloneFields = append(cloneFields, field.Name)
		}
	}

	e.emitComment(fmt.Sprintf("%s uses the 'clone' directive on field(s): %s.", info.Name, strings.Join(cloneFields, ", ")))
	e.emitComment("The generated Clone() method depends on convention-based clone functions that must be")
	e.emitComment("provided by the user. Once those functions are implemented, replace this placeholder")
	e.emitComment("with comprehensive tests for nil safety, round-trip, and mutation independence.")
	e.emitBlankLine()
	e.emitComment("Expected function signatures:")
	for _, field := range info.Fields {
		if field.Directive.Clone {
			fnName := fmt.Sprintf("Clone%s%s", info.Name, field.Name)
			e.emitComment(fmt.Sprintf("  %s(x.%s)", fnName, field.Name))
		}
	}
	e.emitBlankLine()
	e.emitRaw(`t.Skip("clone-tagged fields require user-provided convention functions")`)
	e.indent--
	e.emitRaw("}")
}

// -------------------------------------------- Field Value Generators --------------------------------------------

// testFieldValue returns a Go expression that creates a non-zero test value for the field.
func testFieldValue(field types.FieldInfo) string {
	switch field.TypeCategory {
	case types.CatPrimitive:
		return primitiveTestValue(field.Type)
	case types.CatSlice:
		return sliceTestValue(field)
	case types.CatMap:
		return mapTestLiteral(field)
	case types.CatPtrPrimitive:
		return fmt.Sprintf("ptr(%s)", primitiveTestValue(field.PointedToType))
	case types.CatPtrStruct:
		return fmt.Sprintf("&%s{}", field.PointedToType)
	case types.CatStruct:
		return fmt.Sprintf("%s{}", field.Type)
	case types.CatInterface:
		return "nil"
	case types.CatUnknown:
		return "nil"
	default:
		return "nil"
	}
}

// primitiveTestValue returns a non-zero Go literal for a primitive type.
func primitiveTestValue(typeStr string) string {
	switch typeStr {
	case "string":
		return `"test"`
	case "bool":
		return "true"
	case "int":
		return "1"
	case "int8":
		return "int8(1)"
	case "int16":
		return "int16(1)"
	case "int32":
		return "int32(1)"
	case "int64":
		return "int64(1)"
	case "uint":
		return "uint(1)"
	case "uint8":
		return "uint8(1)"
	case "uint16":
		return "uint16(1)"
	case "uint32":
		return "uint32(1)"
	case "uint64":
		return "uint64(1)"
	case "float32":
		return "float32(1.0)"
	case "float64":
		return "1.0"
	case "byte":
		return "byte(1)"
	case "rune":
		return "rune(65)"
	case "complex64":
		return "complex64(1 + 0i)"
	case "complex128":
		return "complex128(1 + 0i)"
	case "uintptr":
		return "uintptr(1)"
	case "error":
		return `fmt.Errorf("test")`
	default:
		return `""`
	}
}

// sliceTestValue returns a Go literal for a non-empty slice.
func sliceTestValue(field types.FieldInfo) string {
	elem := field.ElemType
	if isBuiltinPrimitive(elem) {
		return fmt.Sprintf("%s{%s, %s}", field.Type, primitiveTestValue(elem), primitiveTestValueAlternate(elem))
	}
	return fmt.Sprintf("%s{{}, {}}", field.Type)
}

// mapTestLiteral returns a Go literal for a non-empty map.
func mapTestLiteral(field types.FieldInfo) string {
	key := field.KeyType
	val := field.ValueType
	return fmt.Sprintf("%s{%s: %s}", field.Type, mapTestKey(key), mapTestValueLiteral(val))
}

// mapTestKey returns a Go expression for a test map key.
func mapTestKey(keyType string) string {
	if keyType == "string" {
		return `"k"`
	}
	if isBuiltinPrimitive(keyType) {
		return primitiveTestValue(keyType)
	}
	return fmt.Sprintf("%s{}", keyType)
}

// mapTestValueLiteral returns a Go expression for a test map value.
func mapTestValueLiteral(valType string) string {
	if isBuiltinPrimitive(valType) {
		return primitiveTestValue(valType)
	}
	return fmt.Sprintf("%s{}", valType)
}

// alternateSliceValue returns a different literal than the default test value, used to detect shared backing memory.
func alternateSliceValue(elemType string) string {
	switch elemType {
	case "string":
		return `"modified"`
	case "bool":
		return "false"
	case "int", "int8", "int16", "int32", "int64":
		return "999"
	case "uint", "uint8", "uint16", "uint32", "uint64":
		return "999"
	case "float32", "float64":
		return "999.0"
	case "byte":
		return "byte(99)"
	case "rune":
		return "rune(90)"
	default:
		return `"modified"`
	}
}

// alternateMapValue returns a different literal for map value mutation.
func alternateMapValue(valType string) string {
	return alternateSliceValue(valType)
}

// primitiveTestValueAlternate returns a second, distinct non-zero literal for a primitive type.
func primitiveTestValueAlternate(typeStr string) string {
	switch typeStr {
	case "string":
		return `"other"`
	case "bool":
		return "false"
	case "int":
		return "2"
	case "int8":
		return "int8(2)"
	case "int16":
		return "int16(2)"
	case "int32":
		return "int32(2)"
	case "int64":
		return "int64(2)"
	case "uint":
		return "uint(2)"
	case "uint8":
		return "uint8(2)"
	case "uint16":
		return "uint16(2)"
	case "uint32":
		return "uint32(2)"
	case "uint64":
		return "uint64(2)"
	case "float32":
		return "float32(2.0)"
	case "float64":
		return "2.0"
	case "byte":
		return "byte(2)"
	case "rune":
		return "rune(66)"
	default:
		return `"other"`
	}
}

// zeroValue returns a Go expression representing the zero value for the field's type.
func zeroValue(field types.FieldInfo) string {
	switch field.TypeCategory {
	case types.CatPrimitive:
		return primitiveZeroValue(field.Type)
	case types.CatSlice, types.CatMap:
		return "nil"
	case types.CatPtrPrimitive, types.CatPtrStruct:
		return "nil"
	case types.CatStruct:
		return fmt.Sprintf("%s{}", field.Type)
	case types.CatInterface:
		return "nil"
	default:
		return "nil"
	}
}

// primitiveZeroValue returns the zero-value expression for a primitive type.
func primitiveZeroValue(typeStr string) string {
	switch typeStr {
	case "string":
		return `""`
	case "bool":
		return "false"
	case "int":
		return "0"
	case "int8":
		return "int8(0)"
	case "int16":
		return "int16(0)"
	case "int32":
		return "int32(0)"
	case "int64":
		return "int64(0)"
	case "uint":
		return "uint(0)"
	case "uint8":
		return "uint8(0)"
	case "uint16":
		return "uint16(0)"
	case "uint32":
		return "uint32(0)"
	case "uint64":
		return "uint64(0)"
	case "float32":
		return "float32(0)"
	case "float64":
		return "0.0"
	case "byte":
		return "byte(0)"
	case "rune":
		return "rune(0)"
	default:
		return `""`
	}
}

// -------------------------------------------- Field Category Predicates --------------------------------------------

// hasPtrPrimitiveFields reports whether the struct has any pointer-to-primitive fields.
func (e *testEmitter) hasPtrPrimitiveFields(info *types.StructInfo) bool {
	for _, field := range info.Fields {
		if field.TypeCategory == types.CatPtrPrimitive {
			return true
		}
	}
	return false
}

// hasDeepContainerFields reports whether the struct has at least one deep-copied container field
// (slice, map, pointer) that requires mutation independence verification.
func (e *testEmitter) hasDeepContainerFields(info *types.StructInfo) bool {
	for _, field := range info.Fields {
		if isDeepCopiedContainer(field) {
			return true
		}
	}
	return false
}

// hasSkipFields reports whether the struct has any skip-tagged fields.
func (e *testEmitter) hasSkipFields(info *types.StructInfo) bool {
	for _, field := range info.Fields {
		if field.Directive.Skip {
			return true
		}
	}
	return false
}

// hasShallowContainerFields reports whether the struct has any shallow-tagged container fields.
func (e *testEmitter) hasShallowContainerFields(info *types.StructInfo) bool {
	for _, field := range info.Fields {
		if field.Directive.Shallow && isContainerType(field.TypeCategory) {
			return true
		}
	}
	return false
}

// hasEmptyFields reports whether the struct has any empty-tagged non-primitive fields.
func (e *testEmitter) hasEmptyFields(info *types.StructInfo) bool {
	for _, field := range info.Fields {
		if field.Directive.Empty && !isPrimitiveCategory(field.TypeCategory) {
			return true
		}
	}
	return false
}

// hasCloneTagFields reports whether the struct has any clone-tagged fields.
func (e *testEmitter) hasCloneTagFields(info *types.StructInfo) bool {
	for _, field := range info.Fields {
		if field.Directive.Clone {
			return true
		}
	}
	return false
}

// isDeepCopiedContainer reports whether a field will be deep-copied (not skip/shallow/empty/clone)
// and has a container type that could expose shared backing memory.
func isDeepCopiedContainer(field types.FieldInfo) bool {
	if field.Directive.Skip || field.Directive.Shallow || field.Directive.Empty || field.Directive.Clone {
		return false
	}
	switch field.TypeCategory {
	case types.CatSlice, types.CatMap, types.CatPtrPrimitive, types.CatPtrStruct, types.CatStruct:
		return true
	}
	return false
}

// isContainerType reports whether the type category is a container (slice, map, or pointer).
func isContainerType(cat types.TypeCategory) bool {
	switch cat {
	case types.CatSlice, types.CatMap, types.CatPtrPrimitive, types.CatPtrStruct:
		return true
	}
	return false
}

// -------------------------------------------- Output Helpers --------------------------------------------

func (e *testEmitter) emitRaw(s string) {
	e.buf.WriteString(strings.Repeat("\t", e.indent))
	e.buf.WriteString(s)
	e.buf.WriteString("\n")
}

func (e *testEmitter) emitBlankLine() {
	e.buf.WriteString("\n")
}

func (e *testEmitter) emitComment(s string) {
	e.emitRaw("// " + s)
}
